export function mountRoomPanel():void{
  const aside=document.querySelector('#tab-world aside')!;
  const settings=document.getElementById('world-seed')!.closest('section')!;aside.prepend(settings);
  const picker=document.createElement('div');picker.innerHTML=`<label>Map <select id="world-map-preset"><option value="procedural">Seeded meadow</option><option value="clear">Clear practice field</option><option value="woods">Woodland · dense</option><option value="imported" disabled>Imported scene</option></select></label><div id="world-map-previews" class="map-thumbnails"></div><div class="toolbar"><button id="world-map-export">Export scene</button><button id="world-map-import">Import scene</button><input id="world-map-file" type="file" accept=".json,application/json" hidden></div><small>Scene files contain terrain, objects and a start pose. This is the 2D Open world format.</small>`;settings.querySelector('.section-title')!.after(picker);
  const panel=document.createElement('section');panel.className='panel-section';panel.id='world-training-tools';panel.innerHTML=`<div class="section-title"><h2>Goal & ghost training</h2></div><button id="world-adapt-racer">Adapt selected racer to room</button><small>Keeps the racer parent. Remaps body feedback and obstacle inputs into room meanings; new inputs start at zero. Load your checkpoint in Track first.</small>
    <label>Exercise <select id="world-task"><option value="forage">Find the flag</option><option value="reverse">Reach a flag behind the start</option></select></label><button id="world-goal-behind">Place flag behind current robot</button>
    <p class="note">Reverse practice ends on arrival. Ghosts have separate physics and compete on identical seeds. Camera estimates, enabled sonar, body feedback and an explicit simulated goal compass reach the controller. Rewards and contact labels only select offspring. A real robot needs a goal localization source.</p>
    <label class="check-row"><input id="world-reverse-coach" type="checkbox" checked><span>Seed a reverse demonstration offspring<small>In reverse practice only: train one child’s motor readout on camera + compass observations from a clear-corridor coach. Original parent still competes unchanged.</small></span></label><label>Contact weight <input id="world-crash-weight" type="range" min="0" max="100" value="20"><output id="world-weight-label">80% arrival speed · 20% fewer contacts</output></label>
    <label>Generations <input id="world-generations" type="number" min="1" max="50" value="3"></label><label>Ghosts per generation <input id="world-population" type="number" min="2" max="16" value="5"></label><label>Time budget · ticks at 30 Hz <input id="world-train-ticks" type="number" min="300" max="3000" step="300" value="900"></label>
    <label>Training speed <select id="world-train-speed"><option value="1">1× · watch</option><option value="4">4×</option><option value="16">16×</option><option value="0" selected>Maximum · CPU limited</option></select></label>
    <div class="toolbar"><button id="world-train" class="primary">Evolve ghosts</button><button id="world-train-stop" disabled>Cancel</button><button id="world-train-adopt" disabled>Use room offspring</button><button id="world-train-report" disabled>Export report</button></div><p id="world-training-status" class="note" role="status">No room trial yet. Eyes stay frozen while controller synapses evolve.</p><div id="world-ghost-scores" class="ghost-scores" aria-live="off"></div>
    <details><summary>Training & sensors console</summary><textarea id="world-sensor-log" readonly rows="7" aria-label="Room sensor and training logs"></textarea><div class="toolbar"><button id="world-copy-logs">Copy logs</button><button id="world-clear-logs">Clear logs</button></div></details><details><summary>Kenyon visual memory</summary><label class="check-row"><input id="world-memory-on" type="checkbox"><span>Recall similar camera views</span></label><label>Kenyon cells <select id="world-memory-count"><option>512</option><option>2048</option><option selected>4096</option><option>10000</option><option>20000</option></select></label><button id="world-memory-forget">Forget visual memory</button><p id="world-memory-status" class="note">Off</p><small>Sparse RGB signatures recall camera clearance estimates; this is not a perfect map or learned reverse policy. Changing capacity starts a fresh memory. Each ghost gets its own fresh memory.</small></details>`;settings.after(panel);
  const tools=document.createElement('div');tools.className='toolbar';tools.innerHTML='<label class="inline"><input id="world-trail-visible" type="checkbox" checked> Crayon driving history</label><button id="world-trail-clear">Clear history</button><button id="world-export-brain">Export room brain + eyes</button>';
  document.querySelector('#tab-world .toolbar')!.after(tools);
  const monitor=document.createElement('section');monitor.className='panel';monitor.innerHTML='<div class="panel-title"><strong>Sonar map · echo history</strong></div><canvas id="world-sonar-map" width="480" height="280" aria-label="Sonar echo history map"></canvas><p class="note">Amber arcs show range with uncertain direction. No echo means unknown, not empty. Uses simulator pose for this diagnostic; excluded from neural inputs. The nominal full beam is 15°, like the 3D view; the simulated sensitivity has soft tails.</p>';document.querySelector('#tab-world .game-card')!.append(monitor);
}
