import { describe,it,expect } from 'vitest';
import { CameraDelay } from './camera-delay';
import { TargetTracker,targetComponents,targetSight } from './target-tracker';
import { BLUE_TARGET,DEFAULT_MODULES,TASK_LEGACY,TASK_TRACKED,taskContract } from './sensor-contract';
import { TaskBrain,taskObservation } from './task-brain';
import { DEFAULT_TASK,taskCase,validateLifecycle } from './lifecycle';
import { DEFAULT_ROBOT } from './model';
import { MotionTelemetry,validateMotionTrace } from './motion-telemetry';
import { taskEnvironment,taskSuite,taskComparisons } from './task-validation';
const pixels=(rects:number[][])=>{const w=32,h=16,n=w*h,f=new Float32Array(n*3).fill(.1);for(const [x,y,dx,dy]of rects)for(let j=y;j<y+dy;j++)for(let i=x;i<x+dx;i++){const k=j*w+i;f[k]=.05;f[n+k]=.3;f[2*n+k]=.95;}return f;};
describe('component tracker and sensor compatibility',()=>{
  it('selects one compact blob rather than averaging separate targets',()=>{const f=pixels([[3,5,4,4],[25,5,3,3]]);expect(targetComponents(f,32,16,BLUE_TARGET)).toHaveLength(2);expect(targetSight(f,32,16,BLUE_TARGET).bearing).toBeLessThan(-.5);const old=taskObservation(f,32,16,DEFAULT_MODULES,BLUE_TARGET,null,[0,0],null,true,TASK_LEGACY),next=taskObservation(f,32,16,DEFAULT_MODULES,BLUE_TARGET,null,[0,0],null);expect(next[28]).toBeLessThan(old[28]-.3);});
  it('keeps identity despite a larger distant distractor and never hallucinates occluded pixels',()=>{const t=new TargetTracker(),a=t.see(pixels([[3,5,4,4]]),32,16,BLUE_TARGET,0);const b=t.see(pixels([[4,5,4,4],[22,3,8,8]]),32,16,BLUE_TARGET,.1);expect(b.id).toBe(a.id);expect(b.bearing).toBeLessThan(-.5);const miss=t.see(pixels([]),32,16,BLUE_TARGET,.2);expect(miss).toMatchObject({id:a.id,visible:false,area:0,bearing:0});expect(t.see(pixels([]),32,16,BLUE_TARGET,.2)).toEqual(miss);t.see(pixels([]),32,16,BLUE_TARGET,.3);expect(t.see(pixels([]),32,16,BLUE_TARGET,.4).id).toBeNull();expect(t.see(pixels([[22,3,8,8]]),32,16,BLUE_TARGET,.5).id).not.toBe(a.id);});
  it('preserves untagged old brains and rejects mismatched contracts',()=>{const b=new TaskBrain(4),s=b.toJSON();expect(s.observation).toBe(TASK_TRACKED);delete s.observation;expect(TaskBrain.fromJSON(s).observation).toBe(TASK_LEGACY);expect(TaskBrain.fromJSON(s).mutate(.1,.1,3).observation).toBe(TASK_LEGACY);expect(()=>TaskBrain.fromJSON({...s,observation:'unknown'})).toThrow();const lab={format:'robot-lifecycle',version:1,brain:b.toJSON(),settings:DEFAULT_TASK,lineage:[],evidence:[],contract:taskContract(TASK_TRACKED,DEFAULT_MODULES,BLUE_TARGET)};expect(validateLifecycle(lab).contract).toEqual(lab.contract);expect(()=>validateLifecycle({...lab,contract:{...lab.contract,recipe:TASK_LEGACY}})).toThrow('contract');});
});
describe('delivered camera latency',()=>{
  it('delivers captured bytes, validity and age together without aliasing',()=>{const d=new CameraDelay(.2),a=new Uint8ClampedArray([10,20,30,255]);expect(d.deliver(a,false,0).dropped).toBe(true);a[0]=90;d.deliver(new Uint8ClampedArray([40,50,60,255]),true,.1);expect(Array.from(d.deliver(a,false,.2).pixels)).toEqual([10,20,30,255]);expect(d.age).toBeCloseTo(.2);expect(d.deliver(a,false,.3).dropped).toBe(true);expect(d.capturedAt).toBe(.1);});
  it('handles paused captures and clock rollback',()=>{const d=new CameraDelay(.2),p=new Uint8ClampedArray([0,0,0,255]);for(let i=0;i<100;i++)d.deliver(p,false,0);expect(d.deliver(p,false,.2).dropped).toBe(false);expect(d.deliver(p,false,0).dropped).toBe(true);expect(()=>d.deliver(p,false,NaN)).toThrow();expect(()=>new CameraDelay(2)).toThrow();});
});
describe('paired room suites',()=>{
  it('pairs scenarios by seed and records reproducible environmental changes',()=>{const cases=taskSuite(42,'empty',2,['current','no-sonar']);expect(cases).toHaveLength(12);for(let i=0;i<cases.length;i+=2)expect({...cases[i+1],variant:'current'}).toEqual(cases[i]);expect(taskEnvironment(42,'stress')).toEqual(taskEnvironment(42,'stress'));expect(taskEnvironment(42,'stress').latency).toBeGreaterThan(taskEnvironment(42,'varied').latency);expect(()=>taskSuite(1,'typo',1,['current'])).toThrow();expect(()=>taskSuite(1,'room',1,['current','current'])).toThrow();});
  it('generates identical geometry for each ablation and varied geometry for challenges',()=>{for(const room of ['empty','room','office']){const a=taskCase(104100,true,DEFAULT_TASK,room,DEFAULT_ROBOT,{profile:'stress',variant:'current'}),b=taskCase(104100,true,DEFAULT_TASK,room,DEFAULT_ROBOT,{profile:'stress',variant:'no-memory'});expect(a).toEqual(b);expect(a.pose).not.toEqual(taskCase(104100,true,DEFAULT_TASK,room).pose);}});
  it('compares matched scores only',()=>{const rows=[{seed:1,variant:'current' as const,success:false,contacts:1,score:2},{seed:1,variant:'single' as const,success:true,contacts:0,score:5},{seed:2,variant:'single' as const,success:false,contacts:1,score:100}];expect(taskComparisons(rows).find(r=>r.variant==='single')).toMatchObject({trials:2,successes:1,pairedScoreDelta:3});expect(taskComparisons(rows.slice(1))[0].pairedScoreDelta).toBeNull();});
});
describe('measured motion telemetry',()=>{
  it('corrects the estimate while keeping command prediction separate',()=>{const m=new MotionTelemetry(DEFAULT_ROBOT);m.issue([.5,.5],0);m.issue([.5,.5],1);const prediction=m.export().samples.at(-1)!.predicted;expect(m.observe({...prediction,z:.025},.02,.04,1)).toBe(true);const row=m.export().samples.at(-1)!;expect(row.predicted).toEqual(prediction);expect(row.estimated.z).toBeGreaterThan(0);expect(m.observe({x:50,z:0,heading:0},.02,.04,1.1)).toBe(false);expect(validateMotionTrace(m.export())).toEqual(m.export());});
  it('uses actual cumulative wheel deltas and resets device-clock baselines explicitly',()=>{const m=new MotionTelemetry(DEFAULT_ROBOT);expect(m.observeWheels(10,2,2,.01,0)).toBe(false);expect(m.observeWheels(11,2.02,2.02,.01,1)).toBe(true);expect(m.wheelSpeed).toBeCloseTo(.02);expect(m.export().samples.at(-1)!.measured!.x).toBeCloseTo(.02);expect(m.observeWheels(10,2,2,.01,2)).toBe(false);expect(()=>m.observeWheels(12,9,9,.01,2)).toThrow('speed');m.resetWheels();expect(m.wheelSpeed).toBeNull();expect(m.observeWheels(1,0,0,.01,3)).toBe(false);});
  it('honours command expiry even when pose feedback continues and validates replay',()=>{const m=new MotionTelemetry(DEFAULT_ROBOT);m.issue([.5,.5],0);for(let time=.5;time<=8;time+=.5)m.observe(m.estimated.pose,.5,.5,time);const rows=m.export().samples;expect(rows.at(-1)!.predicted.x-rows.find(r=>r.time===4)!.predicted.x).toBeLessThan(.001);expect(()=>validateMotionTrace({...m.export(),config:{...DEFAULT_ROBOT,width:0}})).toThrow();expect(()=>validateMotionTrace({...m.export(),samples:[{...rows[0],covariance:[NaN]}]})).toThrow();});
});
