import { TargetTrack } from './target-tracker';
import { TaskChallenge, TaskProfile, TaskVariant, validateChallenge, taskSuite, taskComparisons } from './task-validation';
import { TASK_VIBRATION, TASK_HUNGER, TASK_APPEARANCE, usesVibration, TASK_LEGACY, taskContract, fingerprint } from './sensor-contract';
import { TaskBrain, TASK_INPUT_NAMES, rgbHue } from './task-brain';
import type { Action } from '../core';
import { LifecycleSnapshot, TaskEvidence, TaskSettings, validateTaskSettings } from './lifecycle';
import { EpisodeDataset, EpisodeRecorder, EpisodeStep } from './training';
type Host={snapshot:()=>LifecycleSnapshot;apply:(s:TaskSettings)=>void;transfer:()=>void;setup:(s:TaskSettings,seed:number,heldOut:boolean,room:string,mode:'task'|'coach',challenge?:TaskChallenge)=>void;context:()=>unknown;checkpoint:()=>()=>void;step:()=>EpisodeStep;busy:()=>boolean;pause:()=>void;adopt:(b:TaskBrain,event:string)=>void;evidence:(e:TaskEvidence[])=>void;download:(name:string,text:string)=>void;message:(text:string,error?:boolean)=>void;frame:(r:EpisodeRecorder|null)=>void};
export class LifecyclePanel {
  active=false;retainedAt=0;private kept:EpisodeDataset[]=[];private cancelled=false;private episodeContext:unknown=null;
  constructor(readonly el:HTMLElement,private host:Host){
    el.id='lifecycle-panel';el.className='card lifecycle-panel';el.innerHTML=`<div class="training-head"><div><p class="eyebrow">RACER → EYES → ROOM SKILLS → REAL ROBOT</p><h2>A fly's training journey</h2><p>Keep the parent, train a visual offspring, then test it without sugar or pain reaching its inputs. Start with a blue ball; fetching will need a real pickup mechanism.</p></div><a href="./docs/robot-lifecycle.html">Training guide ↗</a></div>
    <ol class="journey"><li><b>1 · Racer</b><a href="./index.html">Evolve a racer ↗</a><span>Import its checkpoint above; export the parent before adaptation.</span></li><li><b>2 · Eyes</b><a href="./vision.html">Camera-only driving lab ↗</a><span>Train / validate camera driving there. Reward scores are labels, not camera observations.</span></li><li><b>3 · Robot</b><button id="journey-transfer">Adapt racer to room + sonar</button><span>Remap matching body inputs, preserve motor circuit, zero incompatible road inputs; original remains in the exported lineage.</span></li><li><b>4 · Skills</b><span>Demonstrate → train pixels → evolve visual network and fly → held-out test.</span></li><li><b>5 · Hardware</b><a href="#calibration-panel">Calibrate floor & sensors ↓</a><a href="#research-panel">Distill / replay ↓</a><span>USB runs frozen weights and real pixels. Physical transfer remains unmeasured.</span></li></ol>
    <div class="learning-columns"><section><h3>Task & teaching signals</h3><div class="learning-fields"><label>Skill<select id="task-mode"><option value="off">Existing habitat controller</option><option value="approach">Go to a visible target / place marker</option><option value="follow">Follow the moving target</option><option value="forage">Hungry foraging · seek charging / food pod</option></select></label><label>Room<select id="task-room"><option value="empty">Clear floor</option><option value="room">Workshop</option><option value="living">Living room</option><option value="office">Office</option></select></label><label>Sugar on success<input id="task-sugar" type="number" value="10" min="0" max="100"></label><label>Simulated pain / contact<input id="task-pain" type="number" value="1" min="0" max="10"></label><label>Approach shaping<input id="task-shaping" type="number" value="1" min="0" max="5" step=".1"></label><label>Shaping retained / generation<input id="task-fade" type="number" value=".8" min="0" max="1" step=".1"></label><label>Follow continuously · seconds<input id="task-hold" type="number" value="5" min="1" max="20"></label><label>Target path speed · m/s scale<input id="task-speed" type="number" value=".06" min="0" max=".2" step=".01"></label><label>Inherited fly action mix<input id="task-inheritance" type="number" value=".15" min="0" max="1" step=".05"></label><label class="check"><input id="task-recovery-demo" type="checkbox"> Mix forward approach with corner recovery demonstrations</label><label>Trial seed<input id="task-seed" type="number" value="4100" min="0" max="1000000"></label><label>Demo / test duration<input id="task-seconds" type="number" value="12" min="5" max="30"></label></div><div class="row"><button id="task-setup" class="primary">Set up this task</button><button id="task-demo">Collect 3 camera-only coach episodes & train</button><button id="task-neural">Use learned visual network</button><button id="task-validate">Test 3 held-out seeds · frozen weights</button><button id="task-cancel">Cancel job</button></div><p id="task-status" role="status">Task network untrained. The coach is a visible demonstration source; neural tests never use it.</p><progress id="task-progress" value="0" max="100"></progress><small>Evolution below mutates both the visual task network and inherited spiking controller. Sugar is paid once on success; distance-difference shaping fades between generations. Contact penalties are external training labels even when the bumper is off. Held-out tests disable shaping and online reward learning.</small></section>
    <section><h3>Modular senses & colour target</h3><div class="sensor-modules">${['camera','sonar','bumper','light'].map(k=>`<label class="check"><input id="task-module-${k}" type="checkbox" ${['camera','sonar'].includes(k)?'checked':''}> ${k==='bumper'?'Impact input · optional; legacy bumper or SW-420 head':k==='light'?'Light level · derived from camera':k}</label>`).join('')}</div><div class="learning-fields"><label>Ball diameter · cm<input id="task-diameter" type="number" value="6" min="2" max="20" step=".5"></label><label>Target hue · degrees<input id="task-hue" type="number" value="220" min="0" max="359"></label><label>Hue tolerance<input id="task-tolerance" type="number" value="25" min="5" max="60"></label><label>Minimum saturation<input id="task-minSaturation" type="number" value=".35" min=".1" max="1" step=".05"></label><label>Minimum brightness<input id="task-minValue" type="number" value=".18" min=".05" max="1" step=".05"></label></div><label class="check"><input id="task-sample-colour" type="checkbox"> Sample target colour by clicking raw simulated / real camera</label><p>Use a measured real ball diameter and sample its colour under real lighting. The simulated ball is a stationary solid sphere or a scripted moving target; no rolling, grasping or delivery physics yet. A blue place marker uses the same visible target skill.</p><details><summary>Observation contract · ${TASK_INPUT_NAMES.length} channels</summary><p>RGB patch means, valid sonar, previous issued motor commands, visible target bearing / area, optional installed impact sensor and validity bits. The foraging recipe replaces light channels with hunger and charging contact. No position, target coordinates, reward, pain, score or room IDs.</p><pre id="task-contract"></pre></details><p id="task-evidence"></p><button id="task-export">Export journey manifest</button></section></div>`;
    const suite=document.createElement('section');suite.className='task-suite';suite.innerHTML=`<h3>Paired room validation</h3><p>Test the same frozen controller on clear floor, rearranged furniture and noisy office clutter. Starting poses, lighting, grip and camera latency vary by seed. Blue shoes are visual distractors. Each ablation gets the same scene and sensor seed.</p><div class="learning-fields"><label>Teaching / quick-test environment<select id="task-profile"><option value="baseline">Baseline</option><option value="varied">Varied layout, light & delay</option><option value="stress">Noisy clutter & longer delay</option></select></label><label>Seeds per environment<input id="task-suite-count" type="number" min="1" max="3" value="1"></label><label>Seconds per suite trial<input id="task-suite-seconds" type="number" min="5" max="30" value="5"></label></div><div class="row">${['current','single','swarm3','no-memory','no-sonar'].map(v=>`<label class="check"><input type="checkbox" class="task-variant" value="${v}" ${['current','single'].includes(v)?'checked':''}> ${v}</label>`).join('')}</div><div class="row"><button id="task-suite-run">Run paired room suite</button><button id="task-new-tracker">Reset visual head with component tracking</button><button id="task-contract-export">Export sensor contract</button></div><pre id="task-suite-results">No paired room suite yet. More flies or cells require measured benefit.</pre><small>Ablations compare the inherited fly's perception and memory; the visual task head still reads the central raw crop. A small suite is a smoke test, not proof of generalization.</small>`;this.el.append(suite);
    const sw=document.createElement('button');sw.id='task-new-vibration';sw.textContent='New SW-420 visual head · retrain';this.el.querySelector('.sensor-modules')!.after(sw);const note=document.createElement('small');note.textContent='SW-420 head uses held vibration event / validity in slots 30/31. Enable the module in Components & wiring, then retrain. Legacy bumper heads keep their simulated contact input.';sw.after(note);this.on('task-new-vibration',()=>{if(host.busy()){host.message('Finish the current job first.',true);return;}host.pause();const b=new TaskBrain(this.number('task-seed'));b.observation=host.snapshot().settings.mode==='forage'?TASK_HUNGER:host.snapshot().settings.target.appearance?TASK_APPEARANCE:TASK_VIBRATION;host.apply({...this.settings(),modules:{...this.settings().modules,bumper:true}});host.adopt(b,'New SW-420 head: optional impact slots now use vibration pulses; retraining required');this.sync();});
    this.on('task-suite-run',()=>this.runSuite());this.on('task-new-tracker',()=>{const b=new TaskBrain(this.number('task-seed'));b.observation=host.snapshot().settings.mode==='forage'?TASK_HUNGER:host.snapshot().settings.target.appearance?TASK_APPEARANCE:b.observation;host.adopt(b,'New pixel-tracked visual head; retrain before deployment');});this.on('task-contract-export',()=>{const snap=host.snapshot();host.download('robot-sensor-contract.json',JSON.stringify(taskContract(snap.brain.observation??TASK_LEGACY,snap.settings.modules,snap.settings.target),null,2));});
    this.text('task-contract',TASK_INPUT_NAMES.map((n,i)=>`${i}: ${n}`).join('\n'));
    const live=document.createElement('p');live.id='task-live';live.textContent='Visual task observations appear here when the task runs.';this.el.querySelector('#task-status')!.after(live);
    this.on('journey-transfer',()=>host.transfer());this.on('task-setup',()=>host.setup(this.settings(),this.number('task-seed'),false,this.value('task-room'),'task',this.challenge()));this.on('task-neural',()=>host.apply(this.settings()));this.on('task-demo',()=>this.demonstrate());this.on('task-validate',()=>this.validate());this.on('task-cancel',()=>{this.cancelled=true;});this.on('task-export',()=>host.download('robot-training-journey.json',JSON.stringify(host.snapshot(),null,2)));
    for(const id of ['camera','real-camera'])document.getElementById(id)?.addEventListener('click',event=>{if(!this.checked('task-sample-colour')||this.active)return;const canvas=event.currentTarget as HTMLCanvasElement,r=canvas.getBoundingClientRect(),x=Math.min(canvas.width-1,Math.max(0,Math.floor((event.clientX-r.left)/r.width*canvas.width))),y=Math.min(canvas.height-1,Math.max(0,Math.floor((event.clientY-r.top)/r.height*canvas.height))),p=canvas.getContext('2d')!.getImageData(x,y,1,1).data,[h,s,v]=rgbHue(p[0]/255,p[1]/255,p[2]/255);if(s<.1||v<.05){host.message('Choose a brighter, saturated point on the target.',true);return;}this.input('task-hue').value=String(Math.round(h)%360);this.text('task-status',`Sampled hue ${h.toFixed(0)}°, saturation ${s.toFixed(2)}, brightness ${v.toFixed(2)}. Set up task to apply.`);});
  }
  retainedEpisodes():EpisodeDataset[]{return this.kept.map(d=>structuredClone(d));}
  sync():void{this.input('task-recovery-demo').checked=this.host.snapshot().settings.recoveryPractice===true;const snap=this.host.snapshot(),s=snap.settings;this.text('task-contract',`${snap.brain.observation??TASK_LEGACY}\n`+TASK_INPUT_NAMES.map((n,i)=>`${i}: ${usesVibration(snap.brain.observation??TASK_LEGACY)&&i===30?'vibration.event':usesVibration(snap.brain.observation??TASK_LEGACY)&&i===31?'vibration.valid':snap.brain.observation===TASK_HUNGER&&i===32?'energy.hunger':snap.brain.observation===TASK_HUNGER&&i===33?'charger.contact':n}`).join('\n'));for(const k of ['mode','inheritance','sugar','pain','shaping','fade','hold','speed'] as const)this.input('task-'+k).value=String(s[k]);for(const k of ['hue','tolerance','minSaturation','minValue'] as const)this.input('task-'+k).value=String(s.target[k]);this.input('task-diameter').value=String(s.target.diameter*100);for(const k of ['camera','sonar','bumper','light'] as const)this.input('task-module-'+k).checked=s.modules[k];this.text('task-evidence',snap.evidence.length?`${snap.evidence.filter(e=>e.success).length}/${snap.evidence.length} held-out successes · ${snap.evidence.reduce((n,e)=>n+e.contacts,0)} contacts. Simulation evidence only.`:'No held-out task evidence yet.');}
  observe(input:number[],action:Action,source:string,track?:TargetTrack,age=0):void {if(input.length!==35)return;this.text('task-live',`${source==='coach'?'Demonstration coach':'Frozen visual network'} · target ${input[29]>0?'visible':'not seen'}, bearing ${input[28].toFixed(2)}, area cue ${input[29].toFixed(3)} · camera ${input[34]?'valid':'missing'} · sonar ${input[25]?'valid':'unknown / off'} · steer ${action.steer.toFixed(2)}, drive ${action.throttle.toFixed(2)}, reverse ${(action.reverse??0).toFixed(2)} · track ${track?.id??"none"} / ${track?.components??0} blobs · camera age ${(age*1000).toFixed(0)} ms · no reward inputs`);}
  private challenge():TaskChallenge{return validateChallenge({profile:this.value('task-profile') as TaskProfile,variant:'current'});}
  private settings():TaskSettings{const previous=this.host.snapshot().settings;return validateTaskSettings({...previous,mode:this.value('task-mode'),...(this.checked('task-recovery-demo')?{recoveryPractice:true}:previous.recoveryPractice!==undefined?{recoveryPractice:false}:{}),modules:Object.fromEntries(['camera','sonar','bumper','light'].map(k=>[k,this.checked('task-module-'+k)])),target:{...previous.target,hue:this.number('task-hue'),tolerance:this.number('task-tolerance'),minSaturation:this.number('task-minSaturation'),minValue:this.number('task-minValue'),diameter:this.number('task-diameter')/100},...Object.fromEntries(['inheritance','sugar','pain','shaping','fade','hold','speed'].map(k=>[k,this.number('task-'+k)]))});}
  private input(id:string):HTMLInputElement{return this.el.querySelector<HTMLInputElement>('#'+id)!;}
  private value(id:string):string{return this.input(id).value;}
  private checked(id:string):boolean{return this.input(id).checked;}
  private number(id:string):number{const n=Number(this.value(id));if(!Number.isFinite(n))throw new Error('Enter a finite number for '+id);return n;}
  private text(id:string,s:string):void{this.el.querySelector('#'+id)!.textContent=s;}
  private on(id:string,fn:()=>unknown):void{this.el.querySelector('#'+id)!.addEventListener('click',()=>void Promise.resolve().then(fn).catch(e=>this.host.message(String(e),true)));}
  private async job(fn:()=>Promise<void>):Promise<void>{if(this.active||this.host.busy())throw new Error('Finish training/calibration/research and disconnect hardware first.');this.host.pause();const restore=this.host.checkpoint();this.active=true;this.cancelled=false;this.kept=[];const controls=Array.from(document.querySelectorAll<HTMLInputElement>('input,button,select,textarea')).filter(e=>!['task-cancel','copy-log','copy-log-json'].includes(e.id)&&!e.closest('.wb-navigation,.wb-view,#workbench-stop')),disabled=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{await fn();}finally{try{this.host.frame(null);restore();}finally{this.active=false;controls.forEach((e,i)=>e.disabled=disabled[i]);this.sync();}}}
  private async episode(settings:TaskSettings,seed:number,heldOut:boolean,mode:'coach'|'task',challenge=this.challenge(),room=this.value('task-room'),duration=this.number('task-seconds')):Promise<EpisodeDataset>{if(this.cancelled)throw new Error('Journey job cancelled.');this.host.setup(settings,seed,heldOut,room,mode,challenge);this.episodeContext=this.host.context();const recorder=new EpisodeRecorder();this.host.frame(recorder);const seconds=duration;if(!Number.isInteger(seconds)||seconds<5||seconds>30)throw new Error('Trial duration must be 5–30 seconds.');while(recorder.seconds<seconds-1e-8){if(this.cancelled)throw new Error('Journey job cancelled.');for(let i=0;i<3&&recorder.seconds<seconds-1e-8;i++)recorder.step(this.host.step(),1/30);await new Promise<void>(r=>requestAnimationFrame(()=>r()));}this.host.frame(null);const data=recorder.finish(0,0,seed,true);this.kept.push(data);this.retainedAt=Date.now();while(this.kept.length>6)this.kept.shift();return data;}
  private async demonstrate():Promise<void>{const s=this.settings(),seed=this.number('task-seed');if(s.mode==='off')throw new Error('Select a visual target skill.');let learned:TaskBrain|null=null;await this.job(async()=>{const episodes:EpisodeDataset[]=[];for(let i=0;i<3;i++){this.text('task-status',`Camera coach episode ${i+1}/3 · seed ${seed+i}`);episodes.push(await this.episode({...s,...(s.recoveryPractice?{recoveryPractice:i>0}:{})},seed+i,false,'coach'));this.input('task-progress').value=String((i+1)/3*40);}const rows=episodes.map(e=>e.steps.filter(step=>step.diagnostics?.taskInput?.length===35));if(rows.some(r=>r.length<100))throw new Error('Need at least 100 observations per demonstration.');const network=TaskBrain.fromJSON(this.host.snapshot().brain);network.observation=rows[0][0].diagnostics?.taskRecipe??TASK_LEGACY;for(let epoch=0;epoch<60;epoch++){if(this.cancelled)throw new Error('Visual imitation cancelled.');for(const episode of rows.slice(0,2))for(const row of episode)network.learn(row.diagnostics!.taskInput!,row.action,.01);if(epoch%5===0){this.text('task-status',`Learning visual actions · epoch ${epoch+1}/60`);this.input('task-progress').value=String(40+(epoch+1));await new Promise<void>(r=>requestAnimationFrame(()=>r()));}}network.origin='Camera-coach imitation, two train episodes / one held-out episode';const error=rows[2].reduce((sum,row)=>{const a=network.action(row.diagnostics!.taskInput!,row.action,0);return sum+Math.abs(a.steer-row.action.steer)+Math.abs(a.throttle-(a.reverse??0)-(row.action.throttle-(row.action.reverse??0)));},0)/(rows[2].length*2);learned=network;this.text('task-status',`Visual imitation complete · held-out action MAE ${error.toFixed(3)}. This is imitation accuracy; run neural held-out task trials next.`);this.host.download('robot-visual-demonstrations.json',JSON.stringify({format:'robot-visual-demonstrations',version:1,settings:s,episodes,trainingEpisodes:2,validationEpisodes:1,validationActionMAE:error},null,2));});if(learned){this.host.apply(s);this.host.adopt(learned,'Visual imitation: 3 separate coach episodes');}}
  private async validate():Promise<void>{const applied=this.host.snapshot().settings,draft=this.settings();if(JSON.stringify(draft)!==JSON.stringify(applied))throw new Error('Apply the task settings with Use learned visual network or Set up this task before testing. Held-out evidence must describe the applied controller.');const settings={...applied,shaping:0},seed=this.number('task-seed')+100000,room=this.value('task-room');if(settings.mode==='off')throw new Error('Select a task skill.');const evidence:TaskEvidence[]=[],scenario=this.challenge().profile;await this.job(async()=>{for(let i=0;i<3;i++){this.text('task-status',`Frozen neural trial ${i+1}/3 · unseen seed ${seed+i} · no shaping`);const e=await this.episode(settings,seed+i,true,'task');evidence.push({seed:seed+i,heldOut:true,success:e.steps.some(s=>s.evaluation.success),seconds:e.summary.seconds,contacts:e.summary.contacts,score:e.summary.score,source:'neural',shaping:0,room,settings:structuredClone(settings),context:fingerprint(this.episodeContext),scenario,variant:'current'});this.input('task-progress').value=String((i+1)/3*100);}this.text('task-status',`Held-out neural test: ${evidence.filter(e=>e.success).length}/3 successes. No coach, no online learning, no privileged reward inputs. Test more rooms before hardware.`);});this.host.evidence(evidence);this.sync();}
  private async runSuite():Promise<void>{
    const applied=this.host.snapshot().settings;if(JSON.stringify(this.settings())!==JSON.stringify(applied))throw new Error('Apply task settings before paired validation.');if(applied.mode==='off')throw new Error('Select a target skill first.');
    const variants=Array.from(this.el.querySelectorAll<HTMLInputElement>('.task-variant:checked')).map(e=>e.value as TaskVariant);if(!variants.includes('current'))throw new Error('Include current as the paired baseline.');
    const cases=taskSuite(this.number('task-seed'),this.value('task-room'),this.number('task-suite-count'),variants),duration=this.number('task-suite-seconds'),rows:TaskEvidence[]=[],contexts:unknown[]=[],baseline=this.host.context();
    if(!Number.isInteger(duration)||duration<5||duration>30)throw new Error('Suite duration must be 5–30 seconds.');
    await this.job(async()=>{for(const [i,c]of cases.entries()){
      this.text('task-status',`Paired trial ${i+1}/${cases.length} · ${c.room} / ${c.profile} / ${c.variant}`);
      const settings={...applied,shaping:0,modules:{...applied.modules,...(c.variant==='no-sonar'?{sonar:false}:{})}},d=await this.episode(settings,c.seed,true,'task',c,c.room,duration),context=this.episodeContext;contexts.push(context);
      rows.push({seed:c.seed,heldOut:true,success:d.steps.some(s=>s.evaluation.success),seconds:d.summary.seconds,contacts:d.summary.contacts,score:d.summary.score,source:'neural',shaping:0,room:c.room,settings,scenario:c.profile,variant:c.variant,context:fingerprint(context)});
      this.input('task-progress').value=String((i+1)/cases.length*100);
    }});
    this.host.evidence(rows);this.sync();const comparisons=taskComparisons(rows);this.text('task-suite-results',comparisons.map(c=>`${c.variant}: ${c.successes}/${c.trials} successes · ${c.contacts} contacts · paired score Δ ${c.pairedScoreDelta?.toFixed(2)??'unpaired'}`).join('\n'));
    this.text('task-status',`Paired room suite complete · ${rows.length} frozen trials. Lab restored; results include exact contexts and seeds.`);
    this.host.download('robot-task-suite.json',JSON.stringify({format:'robot-task-suite',version:1,generator:'room-challenges-v1',baseline,cases,contexts,results:rows,comparisons,notes:'External reward labels never neural inputs. No online learning. Paired score differences are descriptive; physical transfer is unmeasured.'},null,2));
  }

}
