import type { EpisodeDataset } from './training';
export function validateReplay(raw:unknown):EpisodeDataset {
  const d=raw as EpisodeDataset;
  if(d?.group!==undefined&&(typeof d.group!=='string'||d.group.length>150))throw new Error('Invalid replay group.');
  if(!d||!Array.isArray(d.steps)||!d.steps.length||d.steps.length>1801||!Array.isArray(d.frames)||d.frames.length>1801||!d.summary||Object.values(d.summary).some(v=>typeof v!=='number'||!Number.isFinite(v))||!Number.isInteger(d.omittedFrames)||d.omittedFrames<0)throw new Error('Invalid replay dataset.');
  let previous=-Infinity,bytes=0;const ids=new Set<number>();
  for(const s of d.steps){if(![s.time,s.cameraFrame,s.action?.steer,s.action?.throttle,s.action?.brake,s.evaluation?.pose?.x,s.evaluation?.pose?.z,s.evaluation?.pose?.heading].every(Number.isFinite)||s.time<previous||!Array.isArray(s.inputs)||s.inputs.length>64||s.inputs.some(v=>!Number.isFinite(v))||!Array.isArray(s.pwm)||s.pwm.length!==2||s.pwm.some(v=>!Number.isFinite(v)||Math.abs(v)>255)||typeof s.sonar?.echo!=='boolean'||s.sonar.cm!==null&&(!Number.isFinite(s.sonar.cm)||s.sonar.cm<2||s.sonar.cm>400)||typeof s.evaluation.blocked!=='boolean')throw new Error('Invalid replay step.');previous=s.time;
    if(s.diagnostics){const a=s.diagnostics;if(![a.estimated?.x,a.estimated?.z,a.estimated?.heading,a.odometry?.x,a.odometry?.z,a.odometry?.heading,a.activeCount].every(Number.isFinite)||!Array.isArray(a.covariance)||a.covariance.length!==9||a.covariance.some(v=>!Number.isFinite(v))||!Array.isArray(a.cells)||a.cells.length>200||a.cells.some(v=>!Number.isInteger(v)||v<0||v>=20000)||!Array.isArray(a.estimates)||a.estimates.length>20||a.estimates.some(v=>!Number.isFinite(v))||!Array.isArray(a.requests)||a.requests.length!==2||a.requests.some(v=>!Number.isFinite(v))||!Array.isArray(a.votes)||a.votes.length>5||a.votes.some(v=>![v.steer,v.throttle,v.brake,v.reverse??0].every(Number.isFinite))||!Array.isArray(a.compactInput)||a.compactInput.length!==30||a.compactInput.some(v=>!Number.isFinite(v)||Math.abs(v)>1.01)||!Array.isArray(a.rewards)||a.rewards.length>40||a.rewards.some(v=>typeof v!=='string'||v.length>200))throw new Error('Invalid replay diagnostics.');}
  }
  for(const f of d.frames){if(!Number.isInteger(f.id)||ids.has(f.id)||!Number.isInteger(f.width)||f.width<1||f.width>160||!Number.isInteger(f.height)||f.height<1||f.height>120||f.encoding!=='planar-rgb8-base64'||typeof f.dropped!=='boolean')throw new Error('Invalid replay frame.');ids.add(f.id);for(const pixels of [f.pixels,f.rawPixels].filter((v):v is string=>v!==undefined)){if(typeof pixels!=='string'||pixels.length>76800||!/^[A-Za-z0-9+/]*={0,2}$/.test(pixels)||atob(pixels).length!==f.width*f.height*3)throw new Error('Invalid replay pixels.');bytes+=pixels.length;}if(bytes>8_100_000)throw new Error('Replay exceeds camera budget.');}return structuredClone(d);
}
export function drawReplayFrame(canvas:HTMLCanvasElement,data:EpisodeDataset,id:number,raw=false):void {const ctx=canvas.getContext('2d')!,f=data.frames.find(f=>f.id===id),pixels=raw?f?.rawPixels:f?.pixels;ctx.fillStyle='#142228';ctx.fillRect(0,0,canvas.width,canvas.height);if(!f||!pixels){ctx.fillStyle='#ecbb77';ctx.fillText('Frame not retained',12,24);return;}const bytes=atob(pixels),tmp=document.createElement('canvas');tmp.width=f.width;tmp.height=f.height;const tc=tmp.getContext('2d')!,image=tc.createImageData(f.width,f.height),n=f.width*f.height;for(let i=0;i<n;i++){for(let k=0;k<3;k++)image.data[i*4+k]=bytes.charCodeAt(k*n+i);image.data[i*4+3]=255;}tc.putImageData(image,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,canvas.width,canvas.height);}
