import { describe,it,expect } from 'vitest';
import { DEFAULT_ROBOT } from './model';
import { angle, DEFAULT_CALIBRATION, HeadingPID, StateEstimator, compensate, validateCalibration } from './state-estimator';
import { cameraFov, fitCalibration, fitSonar, markedPlan, MarkRecord, predictMark, validateMarks } from './calibration';
import { pairedReport, trialCase } from './experiments';
import { compactInput, CompactStudent, distill, studentHash, studentPredict, validateStudent } from './compact';
import { compactSketch } from './compact-firmware';
import { ESP_WIRING } from './model';
import { EpisodeRecorder } from './training';
import { validateReplay } from './replay';
import { SugarPolicy } from './objectives';
import { VisualPlaces } from './places';
const origin={x:0,z:0,heading:0};
describe('measured state and control',()=>{
  it('predicts a closed square and retains command uncertainty',()=>{const e=new StateEstimator(origin);for(const segment of markedPlan('square-right',DEFAULT_ROBOT,DEFAULT_CALIBRATION,.5,.55)){e.velocity=[0,0];for(let t=0;t<segment.seconds;t+=1/30)e.predict(segment.pwm,DEFAULT_ROBOT,Math.min(1/30,segment.seconds-t));}expect(Math.hypot(e.pose.x,e.pose.z)).toBeLessThan(.06);expect(e.covariance[0]).toBeGreaterThan(.0004);expect(e.source).toBe('command prediction');});
  it('fuses a plausible noisy pose, wraps headings, and gates outliers',()=>{const e=new StateEstimator({...origin,heading:Math.PI-.01});expect(e.observe({x:.01,z:-.01,heading:-Math.PI+.01},.02,.03,1)).toBe(true);expect(Math.abs(angle(e.pose.heading-Math.PI))).toBeLessThan(.02);expect(e.covariance[0]).toBeLessThan(.0004);const before={...e.pose};expect(e.observe({x:100,z:0,heading:0},.01,.01,2)).toBe(false);expect(e.pose).toEqual(before);expect(()=>e.observe(origin,0,0,0)).toThrow();});
  it('does not invent a lateral fix from a straight wall range',()=>{const e=new StateEstimator(origin);e.covariance=[.04,0,0,0,.04,0,0,0,.04];expect(e.wallRange(180,[1,0],2,.125,.03,1)).toBe(true);expect(e.pose.x).toBeGreaterThan(0);expect(e.pose.z).toBe(0);expect(e.covariance[4]).toBe(.04);expect(e.wallRange(100,[0,1],2,.125,.03,2)).toBe(false);});
  it('PID drops stale feedback and limits integral windup',()=>{const p=new HeadingPID();for(let i=0;i<1000;i++)expect(Math.abs(p.step(2,0,.03,0))).toBeLessThanOrEqual(.25);expect(p.integral).toBe(0);expect(p.step(2,0,.03,1)).toBe(0);expect(p.integral).toBe(0);expect(p.step(0,.1,.03,0)).toBeLessThan(0);});
  it('compensates signed gains and rejects malformed profiles',()=>{expect(compensate([.5,-.5],{...DEFAULT_CALIBRATION,forward:[.5,1],reverse:[1,2]})).toEqual([1,-.25]);expect(()=>validateCalibration({...DEFAULT_CALIBRATION,forward:[0,1]})).toThrow();});
});
describe('floor marks and references',()=>{
  it('records eight square marks with a closed intended path',()=>{for(const kind of ['square-left','square-right'] as const){const plan=markedPlan(kind,DEFAULT_ROBOT,DEFAULT_CALIBRATION);expect(plan).toHaveLength(8);expect(Math.hypot(plan[7].expected.x,plan[7].expected.z)).toBeLessThan(1e-10);expect(Math.abs(plan[7].expected.heading)).toBeLessThan(1e-10);}expect(markedPlan('reverse',DEFAULT_ROBOT,DEFAULT_CALIBRATION)[0].expected.x).toBe(-.5);});
  it('checks reversal and both turn orders without accepting stalled configurations',()=>{const back=markedPlan('out-back',DEFAULT_ROBOT,DEFAULT_CALIBRATION);expect(back).toHaveLength(2);expect(back[1].expected).toEqual(origin);expect(back[1].pwm[0]).toBeLessThan(0);for(const kind of ['turn-left-right','turn-right-left'] as const){expect(markedPlan(kind,DEFAULT_ROBOT,DEFAULT_CALIBRATION)[1].expected.heading).toBeCloseTo(0);}expect(()=>markedPlan('forward',{...DEFAULT_ROBOT,voltage:3,bridgeDrop:4},DEFAULT_CALIBRATION)).toThrow('cannot move');expect(()=>validateMarks([{kind:'forward'}])).toThrow();});
  it('fits effective forward/reverse gains and turn slip from endpoints',()=>{const records:MarkRecord[]=[];const actual={...DEFAULT_CALIBRATION,forward:[.95,1.05] as [number,number],reverse:[.9,1.1] as [number,number],turnLeft:.64,turnRight:.81};for(const kind of ['forward','reverse','left','right'] as const)for(let n=0;n<3;n++){const segment=markedPlan(kind,DEFAULT_ROBOT,DEFAULT_CALIBRATION)[0],nominal=predictMark(origin,segment.pwm,segment.seconds,DEFAULT_ROBOT,DEFAULT_CALIBRATION),truth=predictMark(origin,segment.pwm,segment.seconds,DEFAULT_ROBOT,kind==='forward'||kind==='reverse'?{...actual,turnLeft:.72,turnRight:.72}:actual);records.push({kind,label:segment.label,source:'measured',start:origin,expected:segment.expected,predicted:nominal.pose,measured:truth.pose,seconds:segment.seconds,pwm:segment.pwm,wheelTravel:nominal.travel,sigma:.01,headingSigma:.02,blocked:false,config:DEFAULT_ROBOT});}const fit=fitCalibration(records);expect(fit.profile.forward[0]).toBeCloseTo(.95,2);expect(fit.profile.reverse[1]).toBeCloseTo(1.1,2);expect(fit.profile.turnLeft).toBeCloseTo(.64,2);expect(fit.profile.turnRight).toBeCloseTo(.81,2);expect(fit.used).toBe(12);});
  it('separates demo and measured sources and excludes collisions',()=>{const segment=markedPlan('forward',DEFAULT_ROBOT,DEFAULT_CALIBRATION)[0],nominal=predictMark(origin,segment.pwm,segment.seconds,DEFAULT_ROBOT,DEFAULT_CALIBRATION),record:MarkRecord={kind:'forward',label:'straight',source:'simulation',start:origin,expected:segment.expected,predicted:nominal.pose,measured:nominal.pose,seconds:segment.seconds,pwm:segment.pwm,wheelTravel:nominal.travel,sigma:.01,headingSigma:.02,blocked:false,config:DEFAULT_ROBOT};const measured={...record,source:'measured' as const};expect(fitCalibration([record,measured,{...measured,blocked:true},{...measured,pid:true}]).used).toBe(1);expect(validateMarks([measured])).toEqual([measured]);expect(fitCalibration([]).warnings.length).toBeGreaterThan(3);});
  it('fits sensor references and treats missing echoes explicitly',()=>{const fit=fitSonar([{trueCm:20,readCm:22},{trueCm:50,readCm:52},{trueCm:100,readCm:102},{trueCm:100,readCm:null}]);expect(fit.scale).toBeCloseTo(1);expect(fit.offset).toBeCloseTo(-.02);expect(fit.dropout).toBe(.25);expect(cameraFov(20,50,48)).toBeCloseTo(67.38,1);expect(()=>fitSonar([{trueCm:20,readCm:20}])).toThrow();});
});
describe('research and motor labels',()=>{
  it('keeps training and held-out room layouts distinct and seeded',()=>{expect(trialCase(4,42,true)).toEqual(trialCase(4,42,true));expect(trialCase(4,42,true).objects.map(o=>o.kind)).not.toEqual(trialCase(4,42,false).objects.map(o=>o.kind));expect(trialCase(5,42).harsh).toBe(true);});
  it('computes paired differences only on matching cases',()=>{const base={case:'a',seed:1,stage:0,success:true,timeToGoal:2,contacts:0,distance:1,reward:10,score:30,cpuMs:10,seconds:2};const r=pairedReport([{...base,variant:'current'},{...base,variant:'swarm3',score:32},{...base,seed:99,variant:'swarm3',score:100}]);expect(r[1].scoreDifference).toBe(2);expect(r[1].ci).toBeNull();});
  it('rewards executed right-wheel routing rather than requested left turns',()=>{const p=new SugarPolicy(512);p.action([1],{steer:-1,throttle:1,brake:0},{bearing:-.2,strength:1,antennae:[1,0,0]},0,false,false);p.rememberExecuted([1],[.8,.2]);p.reward(10);const w=p.toJSON().weights;expect(w[5]).toBeGreaterThan(0);expect(w[3]).toBe(0);const idle=new SugarPolicy(512);idle.rememberExecuted([1],[0,0]);idle.reward(10);expect(idle.toJSON().weights.every(v=>v===0)).toBe(true);});
  it('task scoring does not pay for unrelated exploration',()=>{const r=new EpisodeRecorder();r.step({time:0,inputs:[],action:{steer:0,throttle:0,brake:0},pwm:[0,0],cameraFrame:1,sonar:{cm:null,echo:false},evaluation:{pose:origin,blocked:false,contact:null,surface:null,taskReward:10,success:true}},1/30);r.frame(1,1,1,new Float32Array([1,0,0]),false,new Float32Array([0,1,0]));const d=r.finish(1,1,1,true);expect(d.summary.score).toBeCloseTo(30-1/600);expect(validateReplay(d)).toEqual(d);expect(()=>validateReplay({...d,frames:[{...d.frames[0],pixels:'AAAAAA=='}]})).toThrow();});
  it('stores visual topology without truth coordinates and bounds imports',()=>{const p=new VisualPlaces(),e=new StateEstimator(origin);p.observe(Array.from({length:24},(_,i)=>i/24),e,0);p.sugar();expect(p.nodes[0].reward).toBe(true);expect(p.route()).toEqual([0]);expect(VisualPlaces.fromJSON(p.toJSON()).toJSON()).toEqual(p.toJSON());expect(()=>VisualPlaces.fromJSON({version:1,nodes:[{id:8}],edges:[]})).toThrow();});
});
describe('compact onboard student',()=>{
  it('uses the exact RGB565 grid and cue recipe',()=>{const pixels=new Uint8ClampedArray(160*120*4);for(let i=0;i<pixels.length;i+=4){pixels[i]=255;pixels[i+2]=255;pixels[i+3]=255;}const x=compactInput(pixels,110,[.2,-.3]);expect(x).toHaveLength(30);expect(x[0]).toBeCloseTo(248/255,5);expect(x[24]).toBe(.5);expect(x[26]).toBe(.2);expect(x[28]).toBeCloseTo(0);expect(x[29]).toBe(1);});
  it('distils with episode holdout, exports bounded parameters and validates checksums',async()=>{const rows=Array.from({length:240},(_,i)=>({episode:String(Math.floor(i/80)),input:Array(30).fill(i%2?.2:.8),pwm:[.25,-.15] as [number,number]})),s=await distill(rows,()=>{},()=>false,4);expect(s.metrics.trainRows).toBe(160);expect(s.metrics.testRows).toBe(80);expect(s.weights).toHaveLength(398);expect(validateStudent(s)).toEqual(s);expect(studentPredict(s,rows[0].input).every(Number.isFinite)).toBe(true);expect(()=>validateStudent({...s,hash:'oops'})).toThrow();const code=compactSketch(s,ESP_WIRING,DEFAULT_ROBOT);expect(code).toContain('runStudent(fb)');expect(code).toContain('AUTO %d %d');expect(code).toContain('int32_t(millis()-autoUntil)>=0');expect(code).toContain('1500');expect(code).toContain(`STUDENT ${s.hash}`);expect(code).toContain('!autonomous');});
  it('preserves deterministic quantized inference',()=>{const weights=Array(398).fill(0);weights[396]=10;const scales:[number,number]=[.01,.02],s={format:'flykart-compact-student',version:1,recipe:'rgb565-grid30-v1',hidden:12,weights,scales,hash:studentHash(weights,scales),metrics:{},notes:''} as CompactStudent;expect(studentPredict(s,Array(30).fill(0))[0]).toBeCloseTo(Math.tanh(.2));});
});
