import { attachJsonImport } from '../json-import';
import {fingerprint} from './sensor-contract';
import {EpisodeDataset} from './training';
import {TaskEvidence} from './lifecycle';
import {validateReplay} from './replay';
type Entry={format:'robot-run-checkpoint';version:1;id:string;name:string;created:string;lab:unknown;episodes:EpisodeDataset[];evidence:TaskEvidence[];context:string;promoted:boolean};
type Host={lab:()=>unknown;restore:(lab:unknown)=>Promise<void>;validate:(lab:unknown)=>Promise<void>;episodes:()=>EpisodeDataset[];evidence:()=>TaskEvidence[];replay:(e:EpisodeDataset)=>void;busy:()=>boolean;pause:()=>void;download:(name:string,text:string)=>void;message:(s:string,error?:boolean)=>void};
function openStore():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('flykart-robot-runs',1);request.onupgradeneeded=()=>request.result.createObjectStore('runs',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function transaction<T>(mode:IDBTransactionMode,operation:(s:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction('runs',mode),request=operation(tx.objectStore('runs'));tx.oncomplete=()=>{resolve(request.result);db.close();};tx.onerror=tx.onabort=()=>{reject(tx.error??request.error);db.close();};});}
function checkpointContext(lab:unknown):string{const copy=lab as {objects:unknown;config:unknown;noise:unknown;cameraLatency:unknown;learning:{lifecycle?:{settings:unknown;brain:{observation?:string}};visionSettings:unknown;memorySettings:unknown}};return fingerprint({objects:copy.objects,config:copy.config,noise:copy.noise,cameraLatency:copy.cameraLatency,learning:{task:copy.learning.lifecycle?.settings,recipe:copy.learning.lifecycle?.brain.observation,vision:copy.learning.visionSettings,memory:copy.learning.memorySettings}});}
function validateEntry(raw:unknown):Entry{const e=raw as Entry;if(!e||e.format!=='robot-run-checkpoint'||e.version!==1||typeof e.name!=='string'||!e.name.trim()||e.name.length>80||typeof e.created!=='string'||e.created.length>100||!Array.isArray(e.episodes)||e.episodes.length>6||!Array.isArray(e.evidence)||e.evidence.length>100||e.evidence.some(v=>!v||typeof v!=='object')||!e.lab||typeof e.promoted!=='boolean'||typeof e.context!=='string'||!/^[a-f0-9]{8}$/.test(e.context))throw new Error('Invalid checkpoint.');for(const d of e.episodes)validateReplay(d);return {...structuredClone(e),id:crypto.randomUUID(),promoted:false};}
export class RunLibrary {
  readonly el=document.createElement('section');private entries:Entry[]=[];
  constructor(parent:HTMLElement,private host:Host){this.el.className='run-library';this.el.innerHTML=`<p class="eyebrow">SAVE → COMPARE → REPLAY → TRANSFER</p><h3>Training-run library</h3><p>Keep a named brain together with its eyes, target examples, energy recipe, room, wiring, sketch, noise and frozen evidence. Recordings come from the most recent completed task, research or training job and may show that job’s varied cases. Restoring restarts the robot at the saved starting pose with its saved energy. Saved entries use this browser's local database. Export a checkpoint to move it to another computer.</p><div class="row"><label>Checkpoint name<input id="library-name" maxlength="80" placeholder="Pod approach · generation 4"></label><button id="library-save" class="primary">Save current checkpoint</button><button id="library-refresh">Refresh library</button><label>Import checkpoint<input id="library-import" type="file" accept=".json"></label></div><p id="library-status" role="status">Loading local checkpoints…</p><div class="research-table"><table><thead><tr><th>Name / saved</th><th>Evidence</th><th>Replay episodes</th><th>Context</th><th>Actions</th></tr></thead><tbody id="library-rows"></tbody></table></div><p>Compare success, contacts and duration only under matching contexts. A promotion marker requires successful frozen neural trials in at least two different rooms; it is a review aid, not proof of physical transfer.</p><div id="library-failures"><h4>Failure gallery</h4><p>Save an evaluated run to keep failed or collision episodes for replay.</p></div>`;parent.append(this.el);
    this.on('library-save',async()=>{this.ensureIdle();host.pause();const lab=structuredClone(host.lab()),name=(this.el.querySelector<HTMLInputElement>('#library-name')!.value.trim()||'Robot checkpoint');const e:Entry={format:'robot-run-checkpoint',version:1,id:crypto.randomUUID(),name,created:new Date().toISOString(),lab,episodes:host.episodes().slice(-6).map(d=>structuredClone(d)),evidence:structuredClone(host.evidence()),context:checkpointContext(lab),promoted:false};await this.store(e);});
    this.on('library-refresh',()=>this.refresh());attachJsonImport(this.el.querySelector<HTMLInputElement>('#library-import')!,text=>this.importText(text),{title:'Import training checkpoint',maxBytes:40_000_000,busy:()=>host.busy(),onError:detail=>this.status(detail)});void this.refresh();
  }
  private ensureIdle(){if(this.host.busy())throw new Error('Finish the active job and disconnect hardware before restoring or saving a checkpoint.');}
  private status(s:string){this.el.querySelector('#library-status')!.textContent=s;}
  private on(id:string,fn:()=>Promise<void>){this.el.querySelector('#'+id)!.addEventListener('click',()=>void fn().catch(e=>{this.status(String(e));this.host.message(String(e),true);}));}
  private async store(e:Entry){this.ensureIdle();const size=JSON.stringify(e).length;if(size>40_000_000)throw new Error('Checkpoint exceeds 40 MB. Reduce retained episodes or model size.');await this.refresh();if(this.entries.length>=12)throw new Error('Library has 12 entries; export and delete an old entry first.');if(this.entries.reduce((sum,v)=>sum+JSON.stringify(v).length,0)+size>100_000_000)throw new Error('Library exceeds 100 MB. Export and delete an old entry first.');await transaction('readwrite',s=>s.put(e));await this.refresh();this.status('Saved '+e.name+' · full lab and retained episodes.');}
  private async importText(text:string){this.ensureIdle();const e=validateEntry(JSON.parse(text));await this.host.validate(e.lab);if(e.context!==checkpointContext(e.lab))throw new Error('Checkpoint context differs from its saved lab.');const lab=e.lab as {learning?:{lifecycle?:{evidence:TaskEvidence[]}}};if(JSON.stringify(e.evidence)!==JSON.stringify(lab.learning?.lifecycle?.evidence??[]))throw new Error('Checkpoint evidence differs from its saved journey.');await this.store(e);}
  private async refresh(){try{this.entries=(await transaction('readonly',s=>s.getAll()) as Entry[]).sort((a,b)=>b.created.localeCompare(a.created));this.render();this.status(`${this.entries.length} / 12 local checkpoints · export important runs to a file.`);}catch(e){this.status('Local library unavailable: '+String(e));}}
  private render(){const rows=this.el.querySelector('#library-rows')!,gallery=this.el.querySelector('#library-failures')!;rows.replaceChildren();gallery.replaceChildren(Object.assign(document.createElement('h4'),{textContent:'Failure gallery'}));
    for(const e of this.entries){const tr=document.createElement('tr'),cells=Array.from({length:5},()=>document.createElement('td'));cells[0].textContent=e.name+' · '+new Date(e.created).toLocaleString()+(e.promoted?' · promoted':'');const neural=e.evidence.filter(v=>v.heldOut&&v.source==='neural'&&v.shaping===0),success=neural.filter(v=>v.success);cells[1].textContent=`${success.length}/${neural.length} frozen successes · ${neural.reduce((n,v)=>n+v.contacts,0)} contacts`;cells[2].textContent=String(e.episodes.length);cells[3].textContent=e.context;
      const button=(label:string,fn:()=>void|Promise<void>)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>void Promise.resolve().then(fn).catch(err=>this.status(String(err)));cells[4].append(b);return b;};
      button('Restore',async()=>{this.ensureIdle();this.host.pause();await this.host.restore(e.lab);this.status('Restored '+e.name+'. Motors remain paused.');});button('Export',()=>this.host.download('robot-checkpoint-'+e.id+'.json',JSON.stringify(e,null,2)));const promote=button('Mark promoted',async()=>{this.ensureIdle();if(new Set(success.map(v=>v.room).filter(Boolean)).size<2)throw new Error('Need successful frozen neural validation in two named rooms.');e.promoted=true;await transaction('readwrite',s=>s.put(e));this.render();});promote.disabled=e.promoted||new Set(success.map(v=>v.room).filter(Boolean)).size<2;button('Delete',async()=>{this.ensureIdle();await transaction('readwrite',s=>s.delete(e.id));await this.refresh();});tr.append(...cells);rows.append(tr);
      for(const [i,d]of e.episodes.entries()){const last=d.steps.at(-1);if(last?.evaluation.success&&d.summary.contacts===0)continue;const b=document.createElement('button');b.textContent=`Replay ${e.name} · episode ${i+1}: ${d.summary.contacts} contacts / ${d.summary.seconds.toFixed(1)} s / ${last?.evaluation.success?'goal reached':'goal unfinished'}`;b.onclick=()=>{try{this.ensureIdle();this.host.pause();this.host.replay(validateReplay(d));this.status('File replay selected; it does not drive motors.');}catch(err){this.status(String(err));}};gallery.append(b);}
    }
    if(!this.entries.length)rows.append(Object.assign(document.createElement('tr'),{textContent:'No saved checkpoints yet.'}));
  }
}
