import { AppearanceModel, validateAppearance } from './appearance';
export const TASK_INPUT_NAMES = [...Array.from({length:8},(_,i)=>['red','green','blue'].map(c=>`camera.patch${i+1}.${c}`)).flat(), 'sonar.close','sonar.valid','command.left','command.right','target.bearing','target.area','bumper.contact','bumper.valid','light.level','light.valid','camera.valid'];
export const TASK_LEGACY='robot-task35-v1';
export const TASK_TRACKED='robot-task35-tracked-v2';
export const TASK_VIBRATION="robot-task35-sw420-v3";
export const TASK_APPEARANCE='robot-task35-appearance-v4';
export const TASK_HUNGER='robot-task35-energy-v5';
export type TaskRecipe=typeof TASK_LEGACY|typeof TASK_TRACKED|typeof TASK_VIBRATION|typeof TASK_APPEARANCE|typeof TASK_HUNGER;
export const COMPACT_RECIPE='rgb565-grid30-v1';
export const COMPACT_CAMERA={width:160,height:120,top:20,bottom:100,cell:40,cueRed:.55,cueBlue:.45,cueGreenRatio:.78,cueBearing:.18,cueArea:12} as const;
export type SensorModules={camera:boolean;sonar:boolean;bumper:boolean;light:boolean};
export const DEFAULT_MODULES:SensorModules={camera:true,sonar:true,bumper:false,light:false};
export function validateModules(raw:unknown):SensorModules {const s=raw as SensorModules;if(!s||Object.keys(DEFAULT_MODULES).some(k=>typeof s[k as keyof SensorModules]!=='boolean'))throw new Error('Invalid sensor modules.');return {camera:s.camera,sonar:s.sonar,bumper:s.bumper,light:s.light};}
export type ColourTarget={hue:number;tolerance:number;minSaturation:number;minValue:number;diameter:number;appearance?:AppearanceModel};
export const BLUE_TARGET:ColourTarget={hue:220,tolerance:25,minSaturation:.35,minValue:.18,diameter:.06};
export function validateTarget(raw:unknown):ColourTarget {const s=raw as ColourTarget;if(!s||![s.hue,s.tolerance,s.minSaturation,s.minValue,s.diameter].every(Number.isFinite)||s.hue<0||s.hue>=360||s.tolerance<5||s.tolerance>60||s.minSaturation<.1||s.minSaturation>1||s.minValue<.05||s.minValue>1||s.diameter<.02||s.diameter>.2)throw new Error('Invalid target colour/diameter.');return {hue:s.hue,tolerance:s.tolerance,minSaturation:s.minSaturation,minValue:s.minValue,diameter:s.diameter,...(s.appearance?{appearance:validateAppearance(s.appearance)}:{})};}
export function validateTaskRecipe(raw:unknown):TaskRecipe {if(raw!==TASK_LEGACY&&raw!==TASK_TRACKED&&raw!==TASK_VIBRATION&&raw!==TASK_APPEARANCE&&raw!==TASK_HUNGER)throw new Error('Unknown task sensor recipe.');return raw;}
export function usesVibration(recipe:TaskRecipe):boolean{return recipe===TASK_VIBRATION||recipe===TASK_APPEARANCE||recipe===TASK_HUNGER;}
export function rgbHue(r:number,g:number,b:number):[number,number,number] {const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let hue=d===0?0:max===r?60*((g-b)/d%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);return [(hue+360)%360,max===0?0:d/max,max];}
export function taskContract(recipe:TaskRecipe,modules:SensorModules,target:ColourTarget){return {format:'robot-sensor-contract',version:1,recipe:validateTaskRecipe(recipe),inputs:[...TASK_INPUT_NAMES],modules:validateModules(modules),target:validateTarget(target),camera:'planar RGB, centred crop, eight 4×2 patch means',targetCue:recipe===TASK_HUNGER||recipe===TASK_APPEARANCE?'Learned RGB/edge similarity when examples are installed, otherwise colour components; multi-scale scan and temporal association':recipe===TASK_LEGACY?'All matching pixels, one centroid':'Four-connected components; gated temporal association; no invented observation during occlusion',range:{rgb:[0,1],bearing:[-1,1],area:'matching component fraction ×20, clipped to 1',commands:'previous issued PWM /255',sonar:'2–400 cm; close=max(0,1-cm/220); missing=invalid'},light:recipe===TASK_HUNGER?'Slots 32/33 = internal hunger (1-energy) / charging contact; replaces light. Physical inference requires measured battery/charger telemetry.':'camera-derived, requires valid camera',bumper:usesVibration(recipe)?'Slots 30/31 = held SW-420 vibration event / valid. Requires installed module; shaking is not proof of contact. Legacy field names retained for 35-channel weights.':'optional simulation channel; USB bridge has no bumper input',excluded:['pose','object ID','reward','pain','score'],deployment:'Full visual task + spiking fly executes on USB host. Onboard compact student uses a separate 30-channel recipe.'};}
/** Reproducibility checksum, not a security signature. */
export function fingerprint(value:unknown):string {let hash=2166136261;for(const c of JSON.stringify(value)){hash^=c.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');}
