import {describe,it,expect} from 'vitest';
import {APPEARANCE_RECIPE,AppearanceModel,appearanceBoxes,appearanceScore,imageDescriptor,validateAppearance} from './appearance';
import {DEFAULT_HUNGER,EnergyState,validateHunger} from './homeostasis';
import {DEFAULT_GUARD,guardMotors,validateGuard} from './collision-guard';
import {SensorTiming} from './sensor-timing';
import {TASK_HUNGER,TASK_APPEARANCE,BLUE_TARGET,DEFAULT_MODULES} from './sensor-contract';
import {TaskBrain,taskObservation} from './task-brain';
import {DEFAULT_TASK,taskCase,validateLifecycle,validateTaskSettings} from './lifecycle';
import {makeObject,solidsFor} from './model';
import {TargetTracker} from './target-tracker';
import {validateVisual} from './imported-assets';
import {bridgeConfigId} from './esp32-bridge';
import {DEFAULT_ROBOT,ESP_WIRING} from './model';
const frame=(w=32,h=24)=>{const f=new Float32Array(w*h*3);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,target=x>=12&&x<20&&y>=8&&y<16;for(let c=0;c<3;c++)f[c*w*h+i]=target?((x<16)===(y<12)?[.8,.12,.1]:[.1,.75,.2])[c]:[.1,.15,.8][c];}return f;};
describe('learned appearance targets',()=>{
  it('locates a non-blue image pattern with RGB/edge examples and rejects its background',()=>{const f=frame(),positive=imageDescriptor(f,32,24,{x:12,y:8,width:8,height:8}),negative=imageDescriptor(f,32,24,{x:0,y:0,width:8,height:8}),model:AppearanceModel={recipe:APPEARANCE_RECIPE,name:'Patterned charger',positive:[positive],negative:[negative],threshold:.91,margin:.06};expect(appearanceScore(positive,model).score).toBe(1);expect(appearanceScore(negative,model).margin).toBeLessThan(0);const boxes=appearanceBoxes(f,32,24,model);expect(boxes.length).toBeGreaterThan(0);expect(Math.abs(boxes[0].box.x+boxes[0].box.width/2-16)).toBeLessThan(4);const tracker=new TargetTracker(),s=tracker.see(f,32,24,{...BLUE_TARGET,appearance:model},1);expect(s.visible).toBe(true);expect(s.confidence).toBeGreaterThan(.91);expect(tracker.see(f,32,24,{...BLUE_TARGET,appearance:model},2,false).visible).toBe(false);});
  it('round-trips examples and rejects malformed or oversized models',()=>{const model={recipe:APPEARANCE_RECIPE,name:'Pod',positive:[Array(60).fill(.5)],negative:[],threshold:.88,margin:.04};expect(validateAppearance(model)).toEqual(model);expect(()=>validateAppearance({...model,positive:[Array(59).fill(.5)]})).toThrow();expect(()=>validateAppearance({...model,positive:Array(41).fill(Array(60).fill(.5))})).toThrow();expect(()=>validateAppearance({...model,threshold:NaN})).toThrow();});
  it('preserves learned targets and custom specimen dimensions in journey manifests',()=>{const settings=validateTaskSettings({...DEFAULT_TASK,mode:'approach',specimen:makeObject('pod'),target:{...BLUE_TARGET,appearance:{recipe:APPEARANCE_RECIPE,name:'Pod',positive:[Array(60).fill(.5)],negative:[],threshold:.88,margin:.04}}}),brain=new TaskBrain();brain.observation=TASK_APPEARANCE;const saved=validateLifecycle({format:'robot-lifecycle',version:1,settings,brain:brain.toJSON(),lineage:[],evidence:[]});expect(saved.settings.target.appearance?.name).toBe('Pod');expect(taskCase(42,true,settings).ball.kind).toBe('pod');expect(()=>validateTaskSettings({...settings,specimen:{...settings.specimen,width:4}})).toThrow();});
  it('rejects external GLB references and malformed visual data before loading',()=>{expect(()=>validateVisual({type:'glb',name:'pod',data:btoa('not glb')})).toThrow();let json=JSON.stringify({asset:{version:'2.0'},buffers:[{uri:'https://example.com/model.bin',byteLength:4}]});json=json.padEnd(Math.ceil(json.length/4)*4,' ');const bytes=new Uint8Array(20+json.length),d=new DataView(bytes.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,bytes.length,true);d.setUint32(12,json.length,true);d.setUint32(16,0x4e4f534a,true);bytes.set(new TextEncoder().encode(json),20);expect(()=>validateVisual({type:'glb',name:'pod',data:btoa(String.fromCharCode(...bytes))})).toThrow(/External model files/);expect(()=>validateVisual({type:'image',name:'pod',data:'https://example.com/pod.png'})).toThrow();});
  it('decomposes imported model contacts by mesh height, preserving under-clearance',()=>{const o={...makeObject('model'),width:1,depth:1,height:1,visual:{type:'glb' as const,name:'table',data:'fixture',boxes:[{x:0,y:.8,z:0,width:1,height:.1,depth:1},{x:.4,y:.4,z:.4,width:.08,height:.8,depth:.08}]}};const parts=solidsFor(o);expect(parts[0].bottom).toBeCloseTo(.75);expect(parts[1].width).toBe(.08);expect(parts[1].bottom).toBe(0);});
});
describe('energy deficit and food charging',()=>{
  it('does not count a replenishment cycle merely because it starts full',()=>{const e=new EnergyState({...DEFAULT_HUNGER,enabled:true,initial:1,idleDrain:0,motionDrain:0});e.step(.1,0,false);expect(e.cycles).toBe(0);expect(e.charged).toBe(0);});
  it('charges only after stopped contact dwell, rewards real gains, and tapers with satiation',()=>{const settings={...DEFAULT_HUNGER,enabled:true,idleDrain:0,motionDrain:0,dockHold:.2,chargeRate:.1};const e=new EnergyState(settings);expect(e.step(.1,0,false)).toBe(0);expect(e.step(.1,0,true)).toBe(0);const first=e.step(.1,0,true);expect(first).toBeGreaterThan(0);for(let i=0;i<50;i++)e.step(.1,0,true);expect(e.step(.1,0,true)).toBeLessThan(first);for(let i=0;i<100;i++)e.step(.1,0,true);expect(e.energy).toBe(1);expect(e.step(.1,0,true)).toBe(0);expect(e.cycles).toBe(1);e.step(.1,0,false);expect(e.charging).toBe(false);expect(e.hold).toBe(0);});
  it('cannot farm reward by draining and recharging to the same state',()=>{const e=new EnergyState({...DEFAULT_HUNGER,enabled:true,initial:1,idleDrain:.02,motionDrain:0,dockHold:.1,chargeRate:.2});let reward=0;for(let i=0;i<10;i++)reward+=e.step(.1,0,false);for(let i=0;i<10;i++)reward+=e.step(.1,0,true);expect(e.energy).toBe(1);expect(reward).toBeCloseTo(0,12);});
  it('drains with motor effort and keeps old heads and versioned energy semantics distinct',()=>{const e=new EnergyState({...DEFAULT_HUNGER,enabled:true});e.step(1,.8,false);expect(e.energy).toBeLessThan(DEFAULT_HUNGER.initial);const raw=frame(),input=taskObservation(raw,32,24,DEFAULT_MODULES,BLUE_TARGET,50,[0,0],null,true,TASK_HUNGER,undefined,{hunger:.9,charging:true});expect(input).toHaveLength(35);expect(input[32]).toBe(.9);expect(input[33]).toBe(1);expect(()=>validateHunger({...DEFAULT_HUNGER,chargeRate:NaN})).toThrow();expect(()=>validateTaskSettings({...DEFAULT_TASK,mode:'forage'})).toThrow();});
});
describe('independent motor guard and timing',()=>{
  it('requires a matching deployed braking model after wheel speed or voltage changes',()=>{const c={...DEFAULT_ROBOT,guard:{...DEFAULT_GUARD,enabled:true}},id=bridgeConfigId(ESP_WIRING,c);for(const changed of [{rpm:240},{voltage:7.4},{bridgeDrop:1},{wheelDiameter:.07}])expect(bridgeConfigId(ESP_WIRING,{...c,...changed})).not.toBe(id);expect(bridgeConfigId(ESP_WIRING,DEFAULT_ROBOT)).toBe('ESP32CAM:v1:12,13,14,15,-1,-1,2,4:1:1');});
  it('uses stopping distance, handles unknown/stale ranges, and leaves reverse/pivot outside forward coverage',()=>{const s={...DEFAULT_GUARD,enabled:true};expect(guardMotors([.6,.6],2,0,.4,s).pwm).toEqual([0,0]);expect(guardMotors([.6,.6],300,0,.4,s).pwm).toEqual([.6,.6]);expect(guardMotors([.6,.6],300,1,.4,s).pwm).toEqual([0,0]);expect(guardMotors([.6,.6],null,0,.4,s).pwm).toEqual([0,0]);expect(guardMotors([.6,.6],null,0,.4,{...s,unknown:'crawl'}).pwm).toEqual([.15,.15]);expect(guardMotors([-.5,-.5],2,3,.4,s).pwm).toEqual([-.5,-.5]);expect(guardMotors([.5,-.5],2,3,.4,s).pwm).toEqual([.5,-.5]);expect(guardMotors([1,1],300,0,.4,s).stopDistance).toBeGreaterThan(guardMotors([.2,.2],300,0,.4,s).stopDistance);expect(()=>validateGuard({...s,stale:0})).toThrow();});
  it('reports cadence, gaps, latency and unknown readings without inventing echo distance',()=>{const t=new SensorTiming();t.sample('sonar',0,0,true);t.sample('sonar',.067,0,false);t.sample('sonar',.134,0,true);const r=t.report(.234)[0];expect(r.hz).toBeCloseTo(1/.067);expect(r.ageMs).toBeCloseTo(100);expect(r.missing).toBe(1);t.reset();expect(t.report(1)).toEqual([]);});
});
