import {describe,it,expect} from 'vitest';
import {DEFAULT_VIBRATION,validateVibration,VibrationSensor,parseVibrationLine} from './vibration';
import {DEFAULT_ROBOT,ESP_WIRING,wiringIssues,validateRobotConfig} from './model';
import {bridgeSketch,bridgeConfigId} from './esp32-bridge';
import {reconnect,rewritePins} from './rewiring';
import {Firmware,defaultSketch} from './firmware';
import {TASK_VIBRATION,TASK_TRACKED,DEFAULT_MODULES,BLUE_TARGET,taskContract} from './sensor-contract';
import {TaskBrain} from './task-brain';
const settings={...DEFAULT_VIBRATION,enabled:true};
describe('SW-420 digital vibration channel',()=>{
  it('holds a short pulse, suppresses bounce and does not call it force',()=>{const v=new VibrationSensor();expect(v.sample(1,0,settings)).toMatchObject({active:false,valid:true,count:0});expect(v.sample(0,1,settings)).toMatchObject({level:0,active:true,count:1});v.sample(1,3,settings);expect(v.sample(0,5,settings).count).toBe(1);v.sample(1,20,settings);expect(v.sample(0,21,settings).count).toBe(2);expect(v.sample(1,170,settings).active).toBe(true);expect(v.sample(1,171,settings).active).toBe(false);expect(v.sample(0,180,DEFAULT_VIBRATION)).toMatchObject({valid:false,active:false});});
  it('supports reversed polarity and missing sensor validity',()=>{const v=new VibrationSensor();expect(v.sample(0,0,{...settings,activeLow:false}).active).toBe(false);expect(v.sample(1,1,{...settings,activeLow:false}).active).toBe(true);expect(v.sample(1,2,settings,false)).toMatchObject({valid:false,active:false});expect(()=>v.sample(1,0,settings)).toThrow('monotonic');});
  it('has deterministic mount chatter and drive-over triggers independent of collision labels',()=>{const a=new VibrationSensor(6),b=new VibrationSensor(6);for(let i=0;i<100;i++)expect(a.simulate(i*33,settings,0,false,.2,1/30)).toEqual(b.simulate(i*33,settings,0,false,.2,1/30));const v=new VibrationSensor();expect(v.simulate(0,settings,0,true,.2,1/30).active).toBe(true);expect(new VibrationSensor().simulate(0,settings,.3,false,0,1/30).active).toBe(true);});
  it('keeps old labs and heads compatible and tags the new meaning explicitly',()=>{expect(validateRobotConfig(DEFAULT_ROBOT).vibration?.enabled).toBe(false);expect(validateVibration(undefined)).toEqual(DEFAULT_VIBRATION);expect(()=>validateVibration({...settings,holdMs:0})).toThrow();const b=new TaskBrain();expect(b.observation).toBe(TASK_TRACKED);b.observation=TASK_VIBRATION;expect(TaskBrain.fromJSON(b.toJSON()).clone().observation).toBe(TASK_VIBRATION);expect(taskContract(TASK_VIBRATION,{...DEFAULT_MODULES,bumper:true},BLUE_TARGET).bumper).toMatch(/vibration event/);});
  it('rejects conflicts, unwired hardware and unacknowledged LED pad access',()=>{const c={...DEFAULT_ROBOT,vibration:settings};expect(()=>bridgeSketch(ESP_WIRING,c)).toThrow('Connect SW-420');expect(wiringIssues({...ESP_WIRING,vibration:4}).errors).toContain('Two signals share a GPIO.');expect(()=>reconnect(ESP_WIRING,'in1',33)).toThrow('reserved');expect(()=>bridgeSketch({...ESP_WIRING,vibration:1},c)).toThrow('UART');expect(()=>bridgeSketch({...ESP_WIRING,vibration:33},c)).toThrow('confirmation');const w=reconnect(ESP_WIRING,'vibration',33),source=bridgeSketch(w,{...c,vibration:{...settings,gpio33Access:true}});expect(source).toContain('attachInterrupt');expect(source).toContain('count!=vibrationSent');expect(source).toContain('VIB %lu');expect(bridgeConfigId(ESP_WIRING,DEFAULT_ROBOT)).not.toContain('SW420');expect(bridgeConfigId(w,c)).toContain('SW420:33');});
  it('updates a GPIO declaration without replacing user logic and supplies raw / held sketch reads',()=>{const w={...ESP_WIRING,vibration:33},old=defaultSketch(ESP_WIRING)+'\n// keep my custom logic';expect(rewritePins(old,w).source).toContain('const int VIBRATION = 33;');expect(rewritePins(old,w).source).toContain('keep my custom logic');const source='void setup() { pinMode(12, OUTPUT); } void loop() { if (vibrationValid() && vibrationActive() && digitalRead(33) == LOW) { analogWrite(12, 100); } else { analogWrite(12, 0); } delay(1); }',f=new Firmware(source);f.tick({timeMs:0,brainLeft:0,brainRight:0,echoUs:0,wiring:w,vibration:{level:0,active:true,valid:true}});f.tick({timeMs:1,brainLeft:0,brainRight:0,echoUs:0,wiring:w,vibration:{level:0,active:true,valid:true}});expect(f.pins.get(12)).toBe(100);f.tick({timeMs:10,brainLeft:0,brainRight:0,echoUs:0,wiring:w,vibration:{level:1,active:false,valid:true}});expect(f.pins.get(12)).toBe(100);f.tick({timeMs:11,brainLeft:0,brainRight:0,echoUs:0,wiring:w,vibration:{level:1,active:false,valid:true}});expect(f.pins.get(12)).toBe(0);});
  it('parses real digital telemetry and rejects corrupt or unbounded lines',()=>{expect(parseVibrationLine('VIB 500 0 4 1')).toEqual({deviceMs:500,level:0,count:4,active:true});expect(parseVibrationLine('LOG ready')).toBeNull();for(const s of ['VIB 5 2 4 1','VIB 5 0 -1 1','VIB 9999999999999 0 2 1'])expect(()=>parseVibrationLine(s)).toThrow();});
});
