import './parking.css';
import {Action,SpikingNetwork,BrainSnapshot} from '../core';
import {RoomMemory,DEFAULT_MEMORY,MEMORY_SIZES,validateMemorySettings} from '../robot/memory';
import {DEFAULT_VISION,validateVisionSettings} from '../robot/vision-workbench';
import {racerToRoom} from '../robot/task-brain';
import {copyText} from '../robot/serial';
import {attachJsonImport} from '../json-import';
import {mountBrainShelf} from '../browser-brain';
import {loadAssets} from '../vision/ui/assets';
import {importFile} from '../vision/format';
import {widenBrain} from '../vision/inputs';
import {validateVisionModel,VisionModel} from '../vision/perception';
import {drawEye} from '../vision/ui/draw';
import {drawSonarHistory} from '../vision/sonar-history';
import {LESSONS,DEFAULT_PARKING,ParkingSettings,ParkingScene,validateParkingSettings,validateParkingScene,generateParking,Lesson} from './model';
import {ParkingBrain,ParkingSession} from './session';
import {PX} from './episode';
import {trainParking,ParkingTrainingReport} from './training';
import {parkingLab,parseParkingLab,parkingBrainText,parkingRobotScene} from './files';

const root=document.querySelector<HTMLDivElement>('#parking-app')!;
root.innerHTML=`<header><div><div class="eyebrow">FLYKART / LEARNING JOURNEY · STAGE 04</div><h1>Parking simulator<span class="tag">.</span></h1></div><nav><a href="./index.html">1 · Racer</a><a href="./vision.html#track">2 · Vision</a><a href="./vision.html#world">3 · Explore</a><a href="./robot.html">5 · 3D habitat</a><a href="./robot.html#calibration-panel">6 · Calibration</a></nav></header>
<main><div class="toolbar"><button id="run" class="primary">▶ Run fly</button><button id="step">Step 1 s</button><button id="reset">Replay lot</button><button id="new-lot">New random lot</button><label>Lesson<select id="lesson">${LESSONS.map(l=>`<option value="${l.id}">${l.title}</option>`).join('')}</select></label><label>Drive<select id="drive"><option value="fly">Neural fly</option><option value="manual">Manual · WASD / arrows</option></select></label><label>Speed<select id="speed"><option value="1">1×</option><option value="4">4×</option><option value="16">16×</option><option value="0">Maximum</option></select></label></div>
<div class="card import-panel"><div class="row"><b>Load a brain</b><button id="brain-upload" class="primary">Import / paste brain…</button><input id="import-brain" type="file" accept=".json,application/json"><button id="export-brain">Export fly + eyes</button><button id="adapt-racer" disabled>Adapt racer parent to parking</button><span id="brain-name" class="help">Loading world eyes…</span></div><div id="brain-shelf"></div></div>
<div class="metrics"><div class="metric"><b id="quality">0%</b><small>Parking quality · external judge</small></div><div class="metric"><b id="reward">0.0</b><small>Sugar / reward · training only</small></div><div class="metric"><b id="pain">0.0</b><small>Impact + visual-stall pain</small></div><div class="metric"><b id="completion">Searching</b><small>Fit → stop → hold 1 second</small></div></div>
<div class="layout"><section class="card world"><div class="world-head"><b>TOP VIEW / PARKING LOT</b><span id="run-info">Paused</span></div><canvas id="lot" width="1000" height="600" aria-label="Parking lot, bays, moving traffic, pedestrians and independent ghost cars"></canvas><div class="world-foot"><div class="row"><button id="save-state">Save replay lot + brain + memory</button><button id="load-state">Import / paste state…</button><input id="import-state" type="file" accept=".json,application/json"><button id="export-3d">Export 3D scene</button><a href="./robot.html">Open 3D ↗</a></div><small>Pink flag + yellow area mark the target. Cyan is the requested nose; orange is the tail. Click a vacant bay to practise there. Blocks have the robot’s footprint; car skins keep the same contact shape.</small><div id="manual-pad" class="row" hidden><button data-drive="w">↑ Forward</button><button data-drive="a">← Left</button><button id="manual-stop">Stop</button><button data-drive="d">Right →</button><button data-drive="s">↓ Reverse</button><small>Hold a button to drive. Steering works with forward or reverse.</small></div><label class="check"><input id="trail" type="checkbox" checked> Show crayon driving history</label><p id="status" class="status" role="status">Loading…</p></div></section>
<aside class="monitors"><section class="card monitor"><h2>01 / FPV CAMERA <span id="camera-size"></span></h2><canvas id="camera" width="480" height="240" aria-label="Actual low resolution RGB camera pixels"></canvas><small>Actual inference capture, enlarged with nearest-neighbour pixels. Colour, 6.5 cm sensor head.</small></section><section class="card monitor"><h2>02 / FLY EYES · SWARM CROPS</h2><canvas id="eyes" width="480" height="240" aria-label="Actual filtered crop inputs for every fly eye"></canvas><small id="eye-info">Central eye</small><div id="spikes" class="neural"></div></section><section class="card monitor"><h2>03 / SCAN MEMORY · SONAR GROUND MAP</h2><canvas id="scan" width="480" height="280" aria-label="Sonar return evidence ground map"></canvas><div class="monitor-buttons"><button id="scan-view">Perspective / top</button><button id="clear-scan">Clear scan</button></div><small id="sonar-info">HC-SR04 · ~15 Hz · no echo means unknown. Map is a diagnostic, excluded from neural inputs.</small></section></aside></div>
<div class="controls"><section class="card"><h2>Lesson & objective</h2><p id="lesson-help" class="help"></p><div class="fields"><label>Goal cue<select id="cue"><option value="visual">Explore · camera only target</option><option value="compass">Explicit goal compass</option></select></label><label>Learning phase<select id="phase"><option value="shaped">Guided · distance + quality sugar</option><option value="sparse">Sparse · completed parking sugar</option><option value="frozen">Frozen · no sugar / no learning</option></select></label><label>Seed<input id="seed" type="number" min="1" max="999999999"></label><label>Episode time · seconds<input id="seconds" type="number" min="2" max="180" value="30"></label><label>Crash priority <output id="crash-label">20%</output><input id="crash-weight" type="range" min="0" max="1" step=".05" value=".2"></label><label>Arrival criteria<select id="criteria" disabled><option>Entire body + orientation + stop</option></select></label></div><small class="help">Loose lessons allow 27 cm centre tolerance and any direction, but still require stopping. Precise lessons require the full chassis inside the square, heading within 15°, and a contact-free one-second hold. Seeing the flag never wins.</small></section>
<section class="card"><h2>Eyes, memory & traffic</h2><div class="fields"><label>Virtual fly eyes<select id="swarm"><option value="single">1 · central</option><option value="circle3">3 · crop ensemble</option><option value="circle5">5 · crop ensemble</option><option value="circle9">9 · crop ensemble</option><option value="scales3">3 · zoom scales</option></select></label><label>Kenyon visual cells<select id="memory-size">${MEMORY_SIZES.map(n=>`<option value="${n}"${n===4096?' selected':''}>${n.toLocaleString()}</option>`).join('')}</select></label><label>Moving vehicles<input id="traffic-count" type="number" min="0" max="8" value="3"></label><label>Walking pedestrians<input id="pedestrian-count" type="number" min="0" max="8" value="2"></label><label>Rendering / CPU<select id="preview"><option value="full">Full preview</option><option value="low">Low CPU · 5 fps</option><option value="headless">Headless preview</option></select></label><button id="refresh">Refresh views once</button></div><label class="check"><input id="remember" type="checkbox"> Keep visual world memory between live runs</label><label class="check"><input id="cars" type="checkbox"> Replace blocks with car skins</label><label class="check"><input id="jitter" type="checkbox"> Small seeded vehicle-size variations (±4%)</label><label class="check"><input id="normalize" type="checkbox"> Normalize camera contrast</label><button id="forget">Forget visual memory</button><small id="memory-info" class="help">4,096 sparse visual cells. Crops share one physical camera; they are not extra physical viewpoints.</small><small class="help">Traffic lesson: one clockwise lane, following headway, pedestrian priority and parking-yield rules. Walkers visit parked cars; those cars then leave. This is an illustrative traffic model.</small></section>
<section class="card"><h2>Train parking controller offspring</h2><div class="fields"><label>Generations<input id="generations" type="number" min="1" max="50" value="3"></label><label>Ghosts / generation<input id="population" type="number" min="2" max="16" value="6"></label><label>Training speed<select id="training-speed"><option value="0">Maximum · CPU limited</option><option value="16">16×</option><option value="4">4×</option><option value="1">1× · watch</option></select></label><label>Mutation run seed<input id="training-seed" type="number" min="1" max="999999999" value="7331"></label></div><div class="lesson-list" id="curriculum">${LESSONS.map(l=>`<label><input type="checkbox" value="${l.id}" checked>${l.title.slice(5)}</label>`).join('')}</div><small class="help">Always train the active lesson plus a rotating selected lesson on fresh common seeds. Every ghost has its own world. Earlier skills are tested before adoption; ghosts cannot block one another.</small><div class="row actions"><button id="evolve" class="primary">Evolve ghosts</button><button id="cancel" disabled>Cancel</button><button id="adopt" disabled>Use tested offspring</button><button id="export-report" disabled>Export run report</button></div><div class="progress"><div id="training-progress"></div></div><p id="training-status" class="status">Parent remains unchanged until you adopt a tested offspring.</p><details><summary>Teach from your own driving</summary><label class="check"><input id="record-coach" type="checkbox"> Record manual sensor/action examples</label><label class="check"><input id="use-coach" type="checkbox"> Seed one child from those examples</label><small id="coach-info">0 manual examples · capped at 2,000. Other ghosts preserve the parent. Held-out tests still gate adoption.</small></details></section></div>
<details class="card input-audit"><summary>What reaches the fly · transfer & scoring</summary><small>Camera → frozen world vision CNN → clearance estimates; processed RGB → flag bearing/apparent size and two-colour ground-marker direction; HC-SR04 → closeness/strength; body → motor-model speed estimate and last motor requests. Visual mode supplies zero target cue while unseen and never reads target position or compass. Compass mode explicitly uses relative target bearing, distance and heading. Input 15’s open-heading advisory adds observed bay alignment near the target. Pose, crash labels, parking quality, rewards and scan map are external labels, never neural inputs. The inherited CNN was not trained on these lots; measure held-out performance.</small><small>Shaped sugar is a signed change in a distance/quality potential, so driving in circles cannot farm positive rewards. Sparse mode rewards completed parking only. Frozen mode pauses learning and sugar, retaining collision penalties. Pedestrian contact ends the episode; the animation does not alter observations or scores.</small><small>Export fly + eyes imports through Vision and 3D. Save browser brain keeps a separate Parking checkpoint; choose Parking simulator in the 3D browser shelf. Export 3D scene transfers static geometry and a sugar target; its basic sugar judge does not enforce parking containment/orientation. Moving traffic is frozen in that scene. Parking input advisory and renderers differ, so test/retrain before physical use.</small></details>
<section class="card logs"><div class="row"><h2>Sensor & training console</h2><div class="row"><button id="copy-logs">Copy logs · one click</button><button id="save-logs">Save logs</button><button id="clear-logs">Clear</button></div></div><pre id="logs" tabindex="0" aria-label="Copyable sensor and training logs"></pre></section><footer><a href="https://github.com/nomsams/flykart/blob/main/docs/parking-simulator.md">Teaching & transfer guide ↗</a> · Racer → Vision → Explore world → Parking → 3D habitat → Real-world calibration.</footer></main>`;

const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const val=(id:string)=>el<HTMLInputElement>(id).value,num=(id:string)=>Number(val(id)),checked=(id:string)=>el<HTMLInputElement>(id).checked;
let settings={...DEFAULT_PARKING},brain:ParkingBrain,session:ParkingSession,initialScene:ParkingScene,sourceParent:unknown=null,stagedRacer:BrainSnapshot|null=null,stagedParent:unknown=null,stagedMetadata:ParkingBrain['metadata'],racerEyes:VisionModel|null=null;
let running=false,busy=false,cancelled=false,report:ParkingTrainingReport|null=null,ghosts:ParkingSession[]=[],mapPerspective=true,lastPreview=-Infinity,lastPing=-1;
const effectTimes=new WeakMap<object,number>();
const lines:string[]=[],keys=new Set<string>(),demonstrations:{inputs:number[];target:Action}[]=[];
function status(text:string,error=false){el('status').textContent=text;el('status').classList.toggle('error',error);}
function log(text:string){lines.push(`[${session?(session.episode.tick/30).toFixed(2):'0.00'}s] ${text}`);if(lines.length>600)lines.shift();el('logs').textContent=lines.join('\n');}
function save(name:string,text:string){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function setRunning(on:boolean){running=on&&!session.done;el('run').textContent=running?'Ⅱ Pause':'▶ Run fly';}
function safe(action:()=>void|Promise<void>){return()=>{try{const value=action();if(value instanceof Promise)value.catch(e=>status((e as Error).message,true));}catch(e){status((e as Error).message,true);}};}
function readSettings(){return validateParkingSettings({...settings,lesson:val('lesson') as Lesson,cue:val('cue') as ParkingSettings['cue'],phase:val('phase') as ParkingSettings['phase'],seed:num('seed'),maxTicks:num('seconds')*30,crashWeight:num('crash-weight'),traffic:num('traffic-count'),pedestrians:num('pedestrian-count'),cars:checked('cars'),shapeJitter:checked('jitter'),remember:checked('remember')});}
function fill(){for(const [id,v] of Object.entries({lesson:settings.lesson,cue:settings.cue,phase:settings.phase,seed:settings.seed,seconds:settings.maxTicks/30,'crash-weight':settings.crashWeight,'traffic-count':settings.traffic,'pedestrian-count':settings.pedestrians,swarm:brain.visual.layout,'memory-size':brain.memory.count}))el<HTMLInputElement>(id).value=String(v);for(const [id,v] of Object.entries({remember:settings.remember,cars:settings.cars,jitter:settings.shapeJitter,normalize:brain.visual.normalize}))el<HTMLInputElement>(id).checked=v;el('lesson-help').textContent=LESSONS.find(l=>l.id===settings.lesson)!.detail;el('crash-label').textContent=Math.round(settings.crashWeight*100)+'%';el('criteria').innerHTML=`<option>${['arrival','exit','switch'].includes(settings.lesson)?'Yellow area + stop; heading ignored':'Entire body + orientation + stop'}</option>`;}
function rebuild(scene?:ParkingScene){if(busy)throw Error('Stop the training job before editing a lot.');setRunning(false);const remembered=settings.remember&&session&&JSON.stringify(session.memory.settings)===JSON.stringify(brain.memory)?session.memory:undefined;initialScene=scene?validateParkingScene(scene):generateParking(settings);session=new ParkingSession(settings,brain,{scene:initialScene,memory:remembered});lastPing=-1;ghosts=[];fill();render();try{localStorage.setItem('flykart-parking-preferences',JSON.stringify({settings,visual:brain.visual,memory:brain.memory}));}catch{}log(`Lot ${settings.seed} · ${settings.lesson} · ${settings.cue} cue · ${settings.phase} phase · ${remembered?'retained':'fresh'} visual memory`);}
function brainText(){return parkingBrainText(brain,session.memory,settings,sourceParent,report?.brain===brain.controller?report:null);}
function clearExamples(){demonstrations.length=0;report=null;el<HTMLButtonElement>('adopt').disabled=true;el<HTMLButtonElement>('export-report').disabled=true;el('training-progress').style.width='0%';el('training-status').textContent='Input setup changed · train and test again before adopting an offspring.';el('coach-info').textContent='0 manual examples · new input setup. Record manual driving to teach a child.';}
function importBrain(text:string){
  if(busy)throw Error('Cancel evolution before importing.');const parsed=importFile(text),raw=JSON.parse(text);
  if(parsed.kind==='vision-net'){const eyes=validateVisionModel(parsed.vision,'world');clearExamples();brain={...brain,eyes};rebuild(initialScene);status('World camera network installed. Controller retained.');return;}
  if(!parsed.controller)throw Error('A controller is missing.');
  if(parsed.controller.domain==='track'){
    stagedRacer=parsed.controller.snapshot;racerEyes=parsed.world?.vision??null;stagedParent=raw;stagedMetadata={generation:parsed.controller.meta.generation??0,fitness:parsed.controller.meta.fitness??0,track:parsed.controller.meta.track??'all',trainingRecipe:parsed.trainingRecipe};el<HTMLButtonElement>('adapt-racer').disabled=false;el('brain-name').textContent=parsed.name+' · racer parent staged';status('Racer parent kept exactly. Click Adapt racer parent to parking to create room-input offspring; the current parking fly is unchanged.');return;
  }
  const eyes=parsed.vision?validateVisionModel(parsed.vision,'world'):brain.eyes,mem=parsed.worldMemory?RoomMemory.fromJSON(parsed.worldMemory):new RoomMemory(brain.memory),visual=validateVisionSettings(parsed.experiment?.visual??brain.visual);
  const nextBrain:ParkingBrain={...brain,controller:widenBrain(parsed.controller.snapshot),eyes,memory:validateMemorySettings(mem.settings),visual,metadata:{generation:parsed.controller.meta.generation??0,fitness:parsed.controller.meta.fitness??0,track:parsed.controller.meta.track??'all',trainingRecipe:parsed.trainingRecipe}};
  setRunning(false);clearExamples();sourceParent=raw;brain=nextBrain;report=null;stagedRacer=null;el<HTMLButtonElement>('adapt-racer').disabled=true;rebuild(initialScene);session=new ParkingSession(settings,brain,{scene:initialScene,memory:mem});el('brain-name').textContent=parsed.name+' · world weights + eyes';render();status('Imported world controller, eyes, swarm and visual memory. Parking task remains selected. Source weights are preserved; added sonar weights start at zero for a 17-input parent.');
}
function topView(){
  const canvas=el<HTMLCanvasElement>('lot'),c=canvas.getContext('2d')!,w=canvas.width,h=canvas.height,scene=ghosts[0]?.episode.scene??session.episode.scene,scale=Math.min(w/(scene.half*2+.4),h/(scene.half*2+.4));
  const project=(x:number,z:number)=>({x:w/2+x*scale,y:h/2+z*scale});c.fillStyle='#1a2b36';c.fillRect(0,0,w,h);c.strokeStyle='#2b4350';c.lineWidth=1;
  for(let a=-3;a<=3;a+=.25){c.beginPath();c.moveTo(project(a,-3).x,project(a,-3).y);c.lineTo(project(a,3).x,project(a,3).y);c.moveTo(project(-3,a).x,project(-3,a).y);c.lineTo(project(3,a).x,project(3,a).y);c.stroke();}
  const rectangle=(x:number,z:number,heading:number,length:number,width:number,color:string)=>{const p=project(x,z);c.save();c.translate(p.x,p.y);c.rotate(heading);c.fillStyle=color;c.fillRect(-length*scale/2,-width*scale/2,length*scale,width*scale);c.restore();};
  for(const b of scene.bays){const p=project(b.x,b.z);c.save();c.translate(p.x,p.y);c.rotate(b.heading);c.strokeStyle=b.id===scene.target.id?'#ffdb78':'#567783';c.lineWidth=b.id===scene.target.id?3:1.5;c.strokeRect(-b.length*scale/2,-b.width*scale/2,b.length*scale,b.width*scale);c.restore();}
  const b=scene.target,p=project(b.x,b.z);c.strokeStyle='#ffd15d';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,.23*scale,0,Math.PI*2);c.stroke();rectangle(b.x+.14*Math.cos(b.heading),b.z+.14*Math.sin(b.heading),b.heading,.15,.2,'#20e9ed');rectangle(b.x-.14*Math.cos(b.heading),b.z-.14*Math.sin(b.heading),b.heading,.15,.2,'#ff883b');c.fillStyle='#ff73b0';c.fillRect(p.x-1,p.y-18,2,18);c.beginPath();c.moveTo(p.x+1,p.y-18);c.lineTo(p.x+13,p.y-13);c.lineTo(p.x+1,p.y-9);c.fill();
  for(const a of scene.actors){if(a.kind==='pedestrian'){const p=project(a.pose.x,a.pose.z);c.fillStyle='#e9be80';c.beginPath();c.arc(p.x,p.y,a.width*scale/2,0,Math.PI*2);c.fill();}else{rectangle(a.pose.x,a.pose.z,a.pose.heading,a.length,a.width,a.parked?'#627e95':a.yielding?'#c7a457':'#8ca6b8');if(settings.cars){rectangle(a.pose.x,a.pose.z,a.pose.heading,a.length*.35,a.width*.8,'#b5d9e6');for(const side of [-1,1])rectangle(a.pose.x-Math.sin(a.pose.heading)*a.width*.48*side,a.pose.z+Math.cos(a.pose.heading)*a.width*.48*side,a.pose.heading,a.length*.6,.025,'#17232b');}}}
  const colours=['#ffdf83','#86d8ff','#b9a4ff','#8fe3b6','#fb8fbd','#ffba83'];
  const shown=ghosts.length?ghosts:[session];shown.forEach((s,i)=>{if(checked('trail')){c.strokeStyle=colours[i%colours.length]+'99';c.lineWidth=2;c.beginPath();s.episode.trail.forEach((p,j)=>{const q=project(p.x,p.z);j?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y);});c.stroke();}const r=s.episode.physics.pose;rectangle(r.x,r.z,r.heading,.26,.17,colours[i%colours.length]);rectangle(r.x+.09*Math.cos(r.heading),r.z+.09*Math.sin(r.heading),r.heading,.025,.13,'#243946');});
  for(const e of (ghosts[0]??session).episode.effects){const now=performance.now();if(!effectTimes.has(e))effectTimes.set(e,now);const age=(now-effectTimes.get(e)!)/1200;if(age>=1)continue;const p=project(e.x,e.z);c.globalAlpha=1-age;for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=(3+age*25)*(e.kind==='blood'?1:1.3);c.fillStyle=e.kind==='blood'?'#cb334c':e.kind==='explosion'?i%2?'#ffb746':'#ff593b':'#8a9ca9';c.beginPath();c.arc(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,3+age*5,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
  c.fillStyle='#c4d8e2';c.font='13px system-ui';c.fillText('6 × 6 m lot · chassis 26 × 17 cm · '+(ghosts.length?`${ghosts.length} independent ghosts`:'one robot'),14,h-14);
}
function render(){
  if(!session)return;const s=ghosts[0]??session,e=s.episode,q=e.result();topView();drawEye(el('camera'),e.frame,e.camera);
  const members=s.driver.ensemble?.frames.length?s.driver.ensemble.frames:[e.frame],eye=el<HTMLCanvasElement>('eyes'),c=eye.getContext('2d')!,cols=members.length===1?1:3,rows=Math.ceil(members.length/cols),tile=document.createElement('canvas');tile.width=Math.floor(eye.width/cols);tile.height=Math.floor(eye.height/rows);c.clearRect(0,0,eye.width,eye.height);
  members.forEach((f,i)=>{drawEye(tile,f,e.camera);c.drawImage(tile,(i%cols)*tile.width,Math.floor(i/cols)*tile.height);c.fillStyle='#172833c0';c.fillRect(i%cols*tile.width,Math.floor(i/cols)*tile.height,46,15);c.fillStyle='#f4d58a';c.font='10px system-ui';c.fillText(i===0?'CENTRAL':'EYE '+(i+1),i%cols*tile.width+3,Math.floor(i/cols)*tile.height+11);});
  drawSonarHistory(el('scan'),s.scan,e.pose,true,{mode:mapPerspective?'perspective':'top',extent:3*PX});
  el('camera-size').textContent=`${e.camera.width} × ${e.camera.height} · RGB`;el('eye-info').textContent=`${members.length} real crop inputs · ${s.driver.ensemble?.disagreement.toFixed(3)??'0'} disagreement · marker ${s.cue.confidence?'direction seen':'not resolved'}`;
  el('memory-info').textContent=`${s.memory.taught.toLocaleString()} / ${s.memory.count.toLocaleString()} visual cells learned · ${(s.memory.confidence*100).toFixed(0)}% recall confidence. ${settings.remember?'Retained across live replays.':'Fresh on each live replay.'}`;
  el('quality').textContent=Math.round(q.quality*100)+'%';el('reward').textContent=e.status.reward.toFixed(1);el('pain').textContent=e.status.pain.toFixed(1);el('completion').textContent=e.status.success?'Parked ✓':e.status.pedestrianHits?'Pedestrian hit':e.done?'Timed out':e.status.hold?`Hold ${(e.status.hold/30).toFixed(1)}s`:'Searching';el('run-info').textContent=`${(e.tick/30).toFixed(1)} s · ${e.status.contacts} contacts · ${(Math.abs(e.physics.speed)*100).toFixed(1)} cm/s`;
  const sr=e.sonar();el('sonar-info').textContent=`HC-SR04 · ${sr.echo?(sr.range/PX*100).toFixed(1)+' cm':'no echo · unknown'} · ${s.scan.samples.length} pings · marker follows actual contact motion. Map excluded from inputs.`;
  const spikes=s.network.activity().spikes;el('spikes').innerHTML=spikes.map(v=>`<i class="${v?'on':''}"></i>`).join('');
}
function manual():Action{return{steer:(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),throttle:keys.has('arrowup')||keys.has('w') ? .7 : 0,reverse:keys.has('arrowdown')||keys.has('s') ? .6 : 0,brake:keys.has(' ')?1:0};}
function tick(){session.step(val('drive')==='manual'?manual():undefined);if(checked('record-coach')&&val('drive')==='manual'&&demonstrations.length<2000){demonstrations.push({inputs:[...session.driver.sensors],target:manual()});el('coach-info').textContent=`${demonstrations.length} manual examples · use them to seed one child, then test.`;}if(session.episode.sonarUnit.count!==lastPing){lastPing=session.episode.sonarUnit.count;const r=session.episode.sonar();log(`sonar ${r.echo?(r.range/PX*100).toFixed(1)+' cm':'no echo'} · PWM request ${JSON.stringify(session.episode.proprioception())}`);}if(session.done){setRunning(false);const r=session.episode.result();log('Episode complete '+JSON.stringify(r));status(r.success?'Parking complete. Replay this lot, switch lesson, or generate a new lot.':r.pedestrianHits?'Pedestrian contact ended the trial. Review the approach and train avoidance.':'Time budget reached. Inspect the scan and try a shorter lesson or manual demonstrations.');}}
function bind(){
  el('drive').onchange=()=>{keys.clear();el('manual-pad').hidden=val('drive')!=='manual';};
  document.querySelectorAll<HTMLButtonElement>('[data-drive]').forEach(button=>{button.onpointerdown=e=>{if(busy)return;e.preventDefault();button.setPointerCapture(e.pointerId);keys.add(button.dataset.drive!);if(!session.done)setRunning(true);};button.onpointerup=button.onpointercancel=()=>keys.delete(button.dataset.drive!);});el('manual-stop').onclick=()=>keys.clear();
  el('run').onclick=()=>{if(session.done)rebuild(initialScene);setRunning(!running);};el('step').onclick=()=>{setRunning(false);for(let i=0;i<30&&!session.done;i++)tick();render();};el('reset').onclick=safe(()=>{settings=readSettings();rebuild(initialScene);});el('new-lot').onclick=safe(()=>{settings={...readSettings(),seed:1+crypto.getRandomValues(new Uint32Array(1))[0]%999999998};rebuild();status('New seeded lot, vacant bay and start pose.');});
  for(const id of ['lesson','cue','phase','seed','seconds','traffic-count','pedestrian-count','remember','cars','jitter'])el(id).onchange=safe(()=>{settings=readSettings();if(id==='cue')clearExamples();rebuild(id==='lesson'||id==='seed'||id==='traffic-count'||id==='pedestrian-count'||id==='jitter'?undefined:initialScene);});
  el('crash-weight').oninput=()=>{settings.crashWeight=num('crash-weight');el('crash-label').textContent=Math.round(settings.crashWeight*100)+'%';};
  for(const id of ['swarm','normalize','memory-size'])el(id).onchange=safe(()=>{clearExamples();brain={...brain,visual:validateVisionSettings({...brain.visual,layout:val('swarm'),normalize:checked('normalize')}),memory:validateMemorySettings({...brain.memory,count:num('memory-size')})};if(id==='memory-size')session=new ParkingSession(settings,brain,{scene:initialScene});rebuild(initialScene);});
  el('forget').onclick=()=>{session=new ParkingSession(settings,brain,{scene:initialScene});setRunning(false);render();status('Visual memory cleared. Geometry and brain retained.');};el('scan-view').onclick=()=>{mapPerspective=!mapPerspective;render();};el('clear-scan').onclick=()=>{session.scan.clear();render();};el('refresh').onclick=render;el('trail').onchange=render;
  el('export-brain').onclick=()=>save('flykart-parking-brain.json',brainText());el('save-state').onclick=()=>save('flykart-parking-lab.json',JSON.stringify(parkingLab(settings,initialScene,brain,session.memory,session.scan,sourceParent,report)));el('export-3d').onclick=()=>save('parking-3d-scene.json',JSON.stringify(parkingRobotScene(initialScene)));
  attachJsonImport(el<HTMLInputElement>('import-brain'),text=>importBrain(text),{title:'Import parking parent or eyes',trigger:el('brain-upload'),busy:()=>busy,onError:message=>status(message,true)});
  attachJsonImport(el<HTMLInputElement>('import-state'),text=>{const next=parseParkingLab(JSON.parse(text));setRunning(false);clearExamples();sourceParent=next.parent;stagedRacer=null;el<HTMLButtonElement>('adapt-racer').disabled=true;settings=next.settings;brain=next.brain;initialScene=next.scene;session=new ParkingSession(settings,brain,{scene:initialScene,memory:next.memory,learn:false});session.driver.options.learnMemory=settings.phase!=='frozen';session.scan.restore(next.scan.toJSON());report=null;el('brain-name').textContent='Restored parking lab checkpoint';fill();render();status('Lot, exact bay/start, brain, eyes, swarm, scan and visual memory restored. Replay starts a new episode; neural spike state is not serialized.');},{title:'Import parking lot + state',trigger:el('load-state'),busy:()=>busy,onError:message=>status(message,true)});
  el('adapt-racer').onclick=safe(()=>{if(busy)throw Error('Cancel training before adapting.');if(!stagedRacer)return;clearExamples();sourceParent=stagedParent;report=null;brain={...brain,metadata:stagedMetadata,controller:widenBrain(racerToRoom(stagedRacer)),eyes:racerEyes?validateVisionModel(racerEyes,'world'):brain.eyes};stagedRacer=null;el<HTMLButtonElement>('adapt-racer').disabled=true;rebuild(initialScene);el('brain-name').textContent='Racer-derived parking offspring · parent retained';status('Explicit racer → room remapping created an untrained parking child. Parent is retained in exports. Evolve and test before deployment.');});
  mountBrainShelf(el('brain-shelf'),'parking',brainText,text=>importBrain(text),()=>busy);el<HTMLDetailsElement>('brain-shelf').querySelector('details')!.open=false;
  el('copy-logs').onclick=safe(async()=>{await copyText(lines.join('\n'));status('Console copied.');});el('save-logs').onclick=()=>save('parking-logs.json',JSON.stringify({settings,lines,result:session.episode.result()}));el('clear-logs').onclick=()=>{lines.length=0;el('logs').textContent='';};
  el('evolve').onclick=safe(async()=>{
    settings=readSettings();const lessons=Array.from(el('curriculum').querySelectorAll<HTMLInputElement>('input:checked')).map(i=>i.value as Lesson);if(!lessons.length)throw Error('Select at least one rehearsal lesson.');if(!lessons.includes(settings.lesson))lessons.unshift(settings.lesson);
    const generations=num('generations'),population=num('population'),seed=num('training-seed');if(!Number.isInteger(seed)||seed<1||seed>999999999)throw Error('Choose a valid training seed.');
    setRunning(false);busy=true;cancelled=false;report=null;keys.clear();const locked=new Map<HTMLInputElement|HTMLSelectElement|HTMLButtonElement,boolean>();document.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('.controls input,.controls select,.controls button,.toolbar button,.toolbar select,#brain-upload,#adapt-racer,#load-state,#forget').forEach(node=>{if(['preview','refresh','cancel'].includes(node.id))return;locked.set(node,node.disabled);node.disabled=true;});el<HTMLButtonElement>('cancel').disabled=false;el('training-status').textContent='Starting independent camera/sonar ghost worlds…';
    try{report=await trainParking(brain,settings,{generations,population,lessons,seed,speed:num('training-speed'),cancel:()=>cancelled,log:text=>{log(text);el('training-status').textContent=text;},progress:(s,g)=>{ghosts=s;el('training-progress').style.width=Math.round(g/Math.max(1,generations)*100)+'%';},demonstrations:checked('use-coach')?demonstrations:[]});
      if(report)el('training-progress').style.width='100%';
      el('training-status').textContent=report?`Held-out retention ${report.validation.passed?'PASS':'FAIL'} · parent ${report.validation.parent.filter(r=>r.success).length}/${report.lessons.length} · child ${report.validation.offspring.filter(r=>r.success).length}/${report.lessons.length}. ${report.validation.passed?'Use tested offspring to adopt.':'Parent kept; report can be exported.'}`:'Cancelled · original parent retained.';
    }finally{busy=false;ghosts=[];locked.forEach((disabled,node)=>node.disabled=disabled);el<HTMLButtonElement>('cancel').disabled=true;el<HTMLButtonElement>('adopt').disabled=!report?.validation.passed;el<HTMLButtonElement>('export-report').disabled=!report;render();}
  });
  el('cancel').onclick=()=>{cancelled=true;el('training-status').textContent='Cancelling and retaining the parent…';};el('adopt').onclick=safe(()=>{if(!report?.validation.passed)throw Error('Held-out retention failed; parent kept.');if(brain.controller===report.brain)throw Error('This offspring is already adopted.');sourceParent=JSON.parse(brainText());brain={...brain,controller:report.brain,metadata:{...brain.metadata,generation:(brain.metadata?.generation??0)+report.generations,fitness:report.validation.offspring.reduce((a,r)=>a+r.score,0),track:brain.metadata?.track??'all'}};rebuild(initialScene);el<HTMLButtonElement>('adopt').disabled=true;el('brain-name').textContent='Tested parking offspring';status('Tested parking offspring adopted. Export it or save the Parking browser checkpoint.');});el('export-report').onclick=()=>{if(report)save('parking-training-run.json',JSON.stringify(report));};
  el<HTMLCanvasElement>('lot').onpointerdown=safePointer;
  window.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select,textarea')||busy)return;if(e.key==='Escape'){setRunning(false);keys.clear();return;}if(val('drive')==='manual'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase())){e.preventDefault();keys.add(e.key.toLowerCase());}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
}
function safePointer(event:PointerEvent){if(busy)return;const canvas=el<HTMLCanvasElement>('lot'),r=canvas.getBoundingClientRect(),scale=Math.min(canvas.width/6.4,canvas.height/6.4),x=((event.clientX-r.left)/r.width*canvas.width-canvas.width/2)/scale,z=((event.clientY-r.top)/r.height*canvas.height-canvas.height/2)/scale,bay=initialScene.bays.find(b=>!b.occupied&&Math.hypot(b.x-x,b.z-z)<.23);if(bay){try{if(settings.lesson!=='arrival'&&Math.hypot(bay.x-initialScene.start.x,bay.z-initialScene.start.z)<.3)throw Error('Choose a different bay from the starting space.');const next=structuredClone(initialScene);next.target={...bay};rebuild(next);status('Vacant bay selected. Geometry retained; live run restarted.');}catch(e){status((e as Error).message,true);}}}
async function boot(){
  const {assets}=await loadAssets(),eyes=assets.robot?.worldVision??assets.worldVision;if(!eyes)throw Error('Bundled world eyes unavailable. Serve the project with Vite so camera assets can load.');
  brain={controller:widenBrain(assets.robot?.worldController??assets.worldController??new SpikingNetwork(1701).toJSON()),eyes:validateVisionModel(eyes,'world'),visual:{...DEFAULT_VISION},memory:{...DEFAULT_MEMORY}};
  try{const pref=JSON.parse(localStorage.getItem('flykart-parking-preferences')??'null');if(pref){settings=validateParkingSettings(pref.settings);brain.visual=validateVisionSettings(pref.visual);brain.memory=validateMemorySettings(pref.memory);}}catch{log('Invalid saved preferences ignored; original data retained.');}
  initialScene=generateParking(settings);session=new ParkingSession(settings,brain,{scene:initialScene});Object.defineProperty(window,'flykartParking',{value:{get session(){return session;},get brain(){return brain;},get settings(){return {...settings};},get scene(){return structuredClone(initialScene);},get report(){return report;},get busy(){return busy;}}});fill();bind();render();status('Ready · choose a lesson, load a parent, or run the camera/sonar fly.');el('brain-name').textContent='Bundled robot world brain + eyes';
  let previous=performance.now(),accumulator=0;
  const animate=(now:number)=>{if(running&&!busy){const speed=num('speed'),duration=Math.min(.1,(now-previous)/1000);accumulator+=duration*(speed===0?32:speed);const start=performance.now();while(accumulator>=1/30&&!session.done&&performance.now()-start<12){tick();accumulator-=1/30;}if(session.done)accumulator=0;}else accumulator=0;previous=now;if(val('preview')!=='headless'&&now-lastPreview>(val('preview')==='low'?200:40)){render();lastPreview=now;}requestAnimationFrame(animate);};requestAnimationFrame(animate);
}
boot().catch(e=>status((e as Error).message,true));
