import {BrainSnapshot} from './core';
import {importFile} from './vision/format';
export type EvolutionStage='track'|'world'|'parking';
export type GenerationCheckpoint={brain:BrainSnapshot;generation:number;winner:number;score:number;training:Record<string,unknown>};
export type EvolutionRecord={format:'flykart-evolution-generation';version:1;stage:EvolutionStage;at:string;runId:string;runGeneration:number;generation:number;winnerGhost:number;score:number;parentBrainId:string;brainId:string;training:Record<string,unknown>;validation:unknown};
export type EvolutionSave={stage:EvolutionStage;text:string;savedAt:string};
/** Stable weight identity for UI comparison; not a security checksum. */
export function brainIdentity(network:unknown):string{let a=2166136261,b=5381;for(const c of JSON.stringify(network)){a=Math.imul(a^c.charCodeAt(0),16777619);b=Math.imul(b,33)^c.charCodeAt(0);}return 'brain-'+(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0');}
export function describeEvolution(text:string){const raw=JSON.parse(text),parsed=importFile(text);if(!parsed.controller)throw Error('An evolution parent needs a complete controller.');const c=raw.controller??raw;return {raw,network:parsed.controller.snapshot,generation:parsed.controller.meta.generation??0,name:typeof raw.name==='string'?raw.name:'Loaded controller',id:brainIdentity(parsed.controller.snapshot),provenance:Array.isArray(c.provenance)?c.provenance:[],domain:parsed.controller.domain};}
export function evolutionRecords(text:string):EvolutionRecord[]{return describeEvolution(text).provenance.filter((p:EvolutionRecord)=>p?.format==='flykart-evolution-generation'&&p.version===1&&['track','world','parking'].includes(p.stage)&&Number.isInteger(p.generation)&&p.generation>=0&&Number.isFinite(p.score)&&Number.isInteger(p.winnerGhost)&&p.winnerGhost>0&&typeof p.at==='string'&&typeof p.runId==='string'&&typeof p.brainId==='string'&&typeof p.parentBrainId==='string'&&p.training&&typeof p.training==='object');}
/** Portable current setup, with the selected parent weights/history. Eyes stay frozen for this run. */
export function evolutionBase(activeText:string,parentText:string):string{const a=describeEvolution(activeText),p=describeEvolution(parentText);if(a.domain!==p.domain||(a.network.inputCount??17)!==(p.network.inputCount??17))throw Error('Saved evolution parent uses a different domain or input count. Load its checkpoint/setup first, or select the active brain.');const c=a.raw.controller??a.raw;Object.assign(c,{network:p.network,generation:p.generation,provenance:p.provenance});const pc=p.raw.controller??p.raw;for(const key of ['fitness','lineage',...(a.domain==='world'?['trainingRecipe']:[])]){if(pc[key]!==undefined)c[key]=structuredClone(pc[key]);else delete c[key];}if(a.domain==='world'&&a.raw.world)a.raw.world.controller={...c};a.raw.name=p.name;return JSON.stringify(a.raw);}
export function generationFile(baseText:string,previousText:string,stage:EvolutionStage,runId:string,checkpoint:GenerationCheckpoint,baseGeneration:number):string{
 if(!Number.isInteger(checkpoint.generation)||checkpoint.generation<1||!Number.isInteger(checkpoint.winner)||checkpoint.winner<0||!Number.isFinite(checkpoint.score))throw Error('Invalid completed generation.');
 const base=describeEvolution(baseText),previous=describeEvolution(previousText),c=base.raw.controller??base.raw;
 const record:EvolutionRecord={format:'flykart-evolution-generation',version:1,stage,at:new Date().toISOString(),runId,runGeneration:checkpoint.generation,generation:baseGeneration+checkpoint.generation,winnerGhost:checkpoint.winner+1,score:checkpoint.score,parentBrainId:previous.id,brainId:brainIdentity(checkpoint.brain),training:structuredClone(checkpoint.training),validation:'pending held-out tests'};
 Object.assign(c,{network:checkpoint.brain,generation:record.generation,fitness:checkpoint.score,provenance:[...previous.provenance,record]});base.raw.name=`${stage==='track'?'Visual racer':stage==='world'?'Room explorer':'Parking'} offspring · generation ${record.generation}`;if(base.domain==='world'&&base.raw.world)base.raw.world.controller={...c};const text=JSON.stringify(base.raw);describeEvolution(text);return text;
}
export function validatedGeneration(text:string,runId:string,validation:unknown):string{const d=describeEvolution(text),c=d.raw.controller??d.raw,last=Math.max(0,...evolutionRecords(text).filter(p=>p.runId===runId).map(p=>p.generation));c.provenance=d.provenance.map((p:EvolutionRecord)=>p?.format==='flykart-evolution-generation'&&p.runId===runId?{...p,validation:p.generation===last?structuredClone(validation):'Not separately held-out tested; see the final generation of this run.'}:p);if(d.domain==='world'&&d.raw.world)d.raw.world.controller={...c};return JSON.stringify(d.raw);}
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{let settled=false;const fail=(error:unknown)=>{settled=true;reject(error);};const r=indexedDB.open('flykart-evolution-checkpoints',1);r.onupgradeneeded=()=>r.result.createObjectStore('checkpoints',{keyPath:'stage'});r.onsuccess=()=>{if(settled){r.result.close();return;}settled=true;resolve(r.result);};r.onerror=()=>fail(r.error);r.onblocked=()=>fail(Error('Evolution browser storage blocked.'));});}
export async function saveEvolution(stage:EvolutionStage,text:string):Promise<void>{describeEvolution(text);const record:EvolutionSave={stage,text,savedAt:new Date().toISOString()};try{const db=await database();try{await new Promise<void>((resolve,reject)=>{const t=db.transaction('checkpoints','readwrite');t.objectStore('checkpoints').put(record);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}finally{db.close();}}catch{try{localStorage.setItem('flykart.evolution.'+stage,JSON.stringify(record));}catch{throw Error('Browser autosave unavailable/full. The next parent is retained in this tab; export its checkpoint now.');}}}
export async function loadEvolution(stage:EvolutionStage):Promise<EvolutionSave|null>{const records:EvolutionSave[]=[];try{const db=await database();try{const saved=await new Promise<EvolutionSave>((resolve,reject)=>{const r=db.transaction('checkpoints').objectStore('checkpoints').get(stage);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});if(saved)records.push(saved);}finally{db.close();}}catch{}try{const saved=localStorage.getItem('flykart.evolution.'+stage);if(saved)records.push(JSON.parse(saved));}catch{}return records.filter(r=>{try{return r.stage===stage&&typeof r.savedAt==='string'&&Boolean(describeEvolution(r.text));}catch{return false;}}).sort((a,b)=>b.savedAt.localeCompare(a.savedAt))[0]??null;}
