import {describe,it,expect} from 'vitest';
import {SpikingNetwork,DEFAULT_REWARD_CONFIG} from './core';
import {controllerCheckpoint,exportVisionBrain,importFile} from './vision/format';
import {brainIdentity,describeEvolution,evolutionBase,evolutionRecords,generationFile,validatedGeneration} from './evolution-checkpoint';
import {widenBrain} from './vision/inputs';
const network=(seed=1)=>new SpikingNetwork(seed).toJSON();
const file=(domain:'track'|'world'='world',seed=1)=>exportVisionBrain({name:'Imported visual parent',controller:controllerCheckpoint(network(seed),{domain,generation:7,provenance:[{source:'Racer checkpoint',task:'survive racing'}]}),vision:null,fusion:{fade:0,mode:'belief',visionTemperature:1},memory:null,world:null,notes:'Current observation setup'});
const checkpoint=(generation=1,seed=2)=>({generation,brain:network(seed),score:20,winner:1,training:{task:'explore',goalPreset:'far',sonar:true,crashWeight:.2,seeds:[42,43]}});
describe('Evolution continuity and portable history',()=>{
 it('identifies weights independent of file names and generations',()=>{expect(brainIdentity(network())).toBe(brainIdentity(structuredClone(network())));expect(brainIdentity(network())).not.toBe(brainIdentity(network(2)));});
 it('continues from the winner while retaining current observation setup',()=>{const base=file(),first=generationFile(base,base,'world','run-1',checkpoint(),7),secondBase=evolutionBase(file('world',3),first);expect(describeEvolution(secondBase).network).toEqual(network(2));expect(describeEvolution(secondBase).generation).toBe(8);expect(JSON.parse(secondBase).notes).toBe('Current observation setup');expect(JSON.parse(secondBase).controller.fitness).toBe(20);expect(evolutionRecords(secondBase)).toHaveLength(1);});
 it('records current race rewards when continuing, but retains the parent race contract for a room brain',()=>{
  const recipe=(progress:number)=>({version:1,domain:'race',reward:{...DEFAULT_REWARD_CONFIG,progressPerSecond:progress},physics:{wallsEnabled:true,lapTarget:1,impactPain:true,checkpointCount:6,domainRandomization:0},obstacles:{enabled:false,count:0,kind:'mixed'}});
  for(const domain of ['track','world'] as const){const active=JSON.parse(file(domain,1)),parent=JSON.parse(file(domain,2));active.controller.trainingRecipe=recipe(10);parent.controller.trainingRecipe=recipe(20);const next=JSON.parse(evolutionBase(JSON.stringify(active),JSON.stringify(parent)));expect(next.controller.trainingRecipe.reward.progressPerSecond).toBe(domain==='track'?10:20);expect(describeEvolution(JSON.stringify(next)).network).toEqual(network(2));}
 });
 it('keeps cumulative generation, parent IDs and mixed exercise history across runs',()=>{const base=file(),first=generationFile(base,base,'world','one',checkpoint(),7),nextBase=evolutionBase(base,first),second=generationFile(nextBase,nextBase,'world','two',{...checkpoint(1,3),training:{task:'reverse',seeds:[50]}},8),r=evolutionRecords(second);expect(r.map(v=>v.generation)).toEqual([8,9]);expect(r[1].parentBrainId).toBe(r[0].brainId);expect(r.map(v=>v.training.task)).toEqual(['explore','reverse']);expect(JSON.parse(second).controller.provenance[0].source).toBe('Racer checkpoint');expect(importFile(second).controller!.meta.generation).toBe(9);});
 it('marks only the final checkpoint as held-out tested, retaining a usable pending checkpoint on cancellation',()=>{const base=file(),first=generationFile(base,base,'world','run',checkpoint(),7),second=generationFile(base,first,'world','run',checkpoint(2,3),7);expect(evolutionRecords(first)[0].validation).toMatch(/pending/);const tested=validatedGeneration(second,'run',{passed:false,parent:80,offspring:20}),r=evolutionRecords(tested);expect(r[0].validation).toMatch(/Not separately/);expect(r[1].validation).toEqual({passed:false,parent:80,offspring:20});expect(describeEvolution(tested).network).toEqual(network(3));});
 it('rejects incompatible domain/input parents and invalid generation results without replacing a checkpoint',()=>{expect(()=>evolutionBase(file('track'),file())).toThrow(/different domain/);const wide=JSON.parse(file());wide.controller.network=widenBrain(network());expect(()=>evolutionBase(file(),JSON.stringify(wide))).toThrow(/input count/);expect(()=>generationFile(file(),file(),'world','x',{...checkpoint(),score:NaN},7)).toThrow(/Invalid completed/);});
 it('ignores malformed imported history in the UI while retaining other provenance',()=>{const f=JSON.parse(file());f.controller.provenance.push({format:'flykart-evolution-generation',version:1,stage:'world',generation:8,score:null});expect(evolutionRecords(JSON.stringify(f))).toEqual([]);});
});
